### ISSUE TITLE
Strange behaviour on iframe with scrolling set to true

### ISSUE THREAD

**Issue by vigosan** [krakenjs/zoid#105]
Hello,
we are experimenting a strange behavior when using an iframe and we have the `scrolling` set to true:

```
  Payment: xcomponent.create({
    tag: 'fw-payment',
    dimensions: {
      height: '800px',
      width: '100%'
    },  
    url: {
      local: 'http://localhost:5300/',
    },  
    defaultEnv: 'local',
    autoResize: true,
    scrolling: true,
    defaultLogLevel: 'error'
  }), 
```

I'm attaching a video https://cl.ly/3T3l2S332p1X so you can see the effect. It is happening in chrome (mac or window) but not all the computers. Do you have an idea of what the problem could be? Thanks a lot.

**Comment by vigosan** [comment]
@bluepnume any suggestion about this problem?

**Comment by bluepnume** [comment]
I wasn't able to repro this, but if you only want to use vertical resizing you can use:

```
autoResize: {
    height: true,
    width: false
}
```
