### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by namirsab** [krakenjs/zoid#115]
The documentation is poor right now, there are a lot of methods that are not documented and that are realy necessary to make xcomponent useful with changing props for instance.

I'd volunteer to do it but i'd need some time a maybe some guidance :smile:

**Comment by bluepnume** [comment]
I agree. So many other priorities right now that I'm having trouble finding time to give the docs here some much needed love. I'll be happy to give any guidance if you'd like to take a stab at it.

**Comment by namirsab** [comment]
Right now only one method is documented. (Create)
There are so many method that idk if they are public API or not, maybe giving a hint on that topic  would be enough so i can create PRs adding docs for each method.

**Comment by AndyOGo** [comment]
how about proper doclets and auto generaed docs?

**Comment by namirsab** [comment]
@bluepnume i think we should start by documenting at least all the options of `xcomponent.create`
I see there are a lot of undocumented stuff there

**Comment by bluepnume** [comment]
Agreed on that. I just finished a huge effort to get static flow types across all of xcomponent, so now I have a little bandwidth to take up some of this documentation effort.

**Comment by namirsab** [comment]
@bluepnume amazing :smile:
. I'd be really glad to help, i'm now working with xcomponent in my company, so I might have also some questions (so far everything good, but i'd like to add a custom prerender template, i'm not sure how to do that for instance)

**Comment by bluepnume** [comment]
I've taken a good stab at this here: https://github.com/krakenjs/xcomponent/blob/master/docs/api.md

There's still gaps, but this is a pretty comprehensive api doc for 90% of the useful parts of xcomponent. If you could review it and let me know any suggestions that would be awesome! Thanks

**Comment by bluepnume** [comment]
I've also created this demo app that people can fork: https://github.com/krakenjs/xcomponent-demo

**Comment by namirsab** [comment]
@bluepnume just read the article announcing all the repos. Really cool!
I'm gonna take a look to the docs. Thanks a lot!

**Comment by namirsab** [comment]
@bluepnume just checked the docs, looking good in general, just missing info about what you can find in the iframe `window` like `window.child.onProps` and things like that.
I think those are used for more complex use cases.

If you can tell me which file implements those features, i can take a look and make a PR :smile:

**Comment by bluepnume** [comment]
Everything on `window.xchild` is implemeted here: https://github.com/krakenjs/xcomponent/blob/master/src/component/child/index.js

Problem is a lot of those methods aren't intended to be public, but I was lazy when building this for the first time and just exposed the entire class as `window.xchild` :D so I don't necessarily want to add public docs for all of it. I'll add stuff like `onProps` though, thanks for reminding me.
