### ISSUE TITLE
Add teardown for button

### ISSUE THREAD

**Issue by TopsyCM** [krakenjs/zoid#116]
I'm integrating PayPal checkout in an ember app and am trying to avoid accumulating memory leaks. I have an ember component that calls `paypal.Button.render(...)`. Rendering that component adds listeners, etc, but unrendering it does not clear them. Watching the performance tab in Chrome and toggling the button on and off shows a steady increase in memory use and listeners.

I was looking at the existing framework integrations (Angular, React), but I don't see any teardown implemented in those. Is the Button supposed to handle teardown itself in a single-page app? Are there public methods for teardown? I saw teardown functions in `xcomponent`, but I was unable to figure out how to use them.

**Comment by bluepnume** [comment]
Hi @TopsyCM! Thanks for the report. There's definitely teardown for all of the windows/events/etc. in xcomponent, that should be happening automatically whenever the iframe is removed or closed. We run 600+ tests over in the paypal-checkout repo in the same karma chrome window, and those tests automatically fail if the memory usage crosses a 350mb threshold during all of the renders and teardowns.

So, that said, I'm interested to know more about your case. If something is slipping through the cracks, I'd like to track it down -- in your case:

- How is the button being destroyed? Is it just being removed from the DOM?
- Do you have a test page where I can try this for myself?
- Are there any specific listeners which you're seeing hanging around, so I can check they're being torn-down correctly?

**Comment by TopsyCM** [comment]
Hello! Perhaps I am misinterpreting what I'm seeing in the inspector. I will run some more tests to confirm tomorrow. As for your questions:

- The button is being removed from the DOM via a conditional in the template. The html element that is addressed by the `paypal.Button.render` call is being removed.
- I'll see if I can set up a fiddle or twiddle or some kind of "iddle" that demonstrates this.
- I have not identified any specific listeners yet, just watching things go up in the inspector and not come back down.

**Comment by bluepnume** [comment]
OK sounds good! I'll take a look too and see if anything shows up.

**Comment by TopsyCM** [comment]
I have created a simple example here:
https://topsycm.github.io/paypal-demo/

I have added the `paypal.Button.render` command to a simple component. That component is then rendered or not based on a boolean value that can be toggled with the "toggle" button. What I've been doing is taking a heap snapshot in Chrome devtools on a fresh page load, then I toggle the button a few times, then I take another snapshot. I've also used the performance tab to record memory use while toggling the button and triggering GC.

Is this behaving like you expect?

I have duplicated the test (locally) using a couple of different components, and there is no increase in resource usage after toggling.

**Comment by bluepnume** [comment]
Hmm yeah, after toggling the button a few times and taking a few snapshots, I am seeing memory not being cleared up. Wonder why this isn't being caught by the memory checks in the tests in `paypal-checkout`.

Let me try to find some time to dig a little further into this, this week. Thanks again for the heads up.

**Comment by TopsyCM** [comment]
@bluepnume Have you had any time to investigate this? It's not the kind of thing that is likely to cause problems for our users, but I would prefer to not leak memory.

**Comment by bluepnume** [comment]
Hey, sorry -- been tied up with a bunch of other things and haven't had a lot of time to drill down into this. I'll try to carve out some time -- in the mean time, if you find any evidence of any specific objects not being GC'd, I'd be glad to make specific fixes or accept any PRs. Thanks again for your time so far.

**Comment by TopsyCM** [comment]
Alas, I am not rolling in free time myself right now. If I am overtaken by idleness, I'll take a closer look.

**Comment by namirsab** [comment]
@bluepnume @TopsyCM are there any news regarding this topic?
is it a generic issue? or an specific case?

**Comment by TopsyCM** [comment]
@namirsab Seemed to be pretty generic to me, though it's the kind of thing that would primarily affect single page apps. You can take a look at the example I posted above.

**Comment by namirsab** [comment]
@TopsyCM thanks!
That's the issue, i'm working on a single page app... we'll see
