### ISSUE TITLE
No handler found for post message

### ISSUE THREAD

**Issue by andychong1996** [krakenjs/zoid#121]
Hi,

This error is raised on one of the site where a xcomponent component loaded. The situation is a little weird, because the error only happens in the mobile browser, or during I inspect and open the developer console.

<img width="997" alt="screen shot 2017-09-29 at 1 36 39 pm" src="https://user-images.githubusercontent.com/12697240/31007473-4aed4a16-a533-11e7-80db-7a44c385971e.png">

<img width="997" alt="screen shot 2017-09-29 at 1 36 59 pm" src="https://user-images.githubusercontent.com/12697240/31007496-5768b5a0-a533-11e7-8335-0c7bbcd1c6fb.png">

<img width="998" alt="screen shot 2017-09-29 at 1 37 08 pm" src="https://user-images.githubusercontent.com/12697240/31007500-5a8b11d8-a533-11e7-9c20-2ceaacf84d2b.png">

**Comment by andychong1996** [comment]
Hi @bluepnume , do you have any idea what potentially triggers this error? It is a little weird that this only happens on the mobile browser, or during developer console view, and only for this one particular site.

**Comment by bluepnume** [comment]
Hi @andychong1996 -- I'm having a little trouble reproducing this. I'm trying on majordrop.com with the developer console open, but I don't see the error. Can you give me any more specific steps to reproduce in desktop chrome?

**Comment by andychong1996** [comment]
Hi @bluepnume , the reason there is no error is because the site with the current theme has no problem.  Where the other theme is having the problem. I'm trying to find out a way so that you can reproduce on the particular theme. Btw, I reload the web page a few times, and I saw this on the log `xc_postco_widget_detect_close_child`, and then `xc_postco_widget_destroy`. In what situation this will be triggered?

![screen shot 2017-10-02 at 11 01 21 pm](https://user-images.githubusercontent.com/12697240/31084098-198ff4d8-a7c6-11e7-9c52-77b05feb977f.png)

**Comment by andychong1996** [comment]
Hi @bluepnume , what I found out is that somehow the library used in the store's theme:
 [https://github.com/FrDH/jQuery.mmenu](url) is destroying the parent iframe on its initialization(guessing). I'm not super sure how to find out where the conflict is. I comment out the library code, then it is fine. Currently, my temporary solution is just put a `setTimeout` on the script to initialize the xcomponent.

**Comment by bluepnume** [comment]
Interesting. I'll try to repro with jQuery.mmenu -- in the mean time if you have any simple example code where I can see the issue / conflict, that would be really useful. Glad you found a temporary fix.

**Comment by lucaizzo** [comment]
I solved wrapping the button init function in $(window).load()
