### ISSUE TITLE
Demo Request - Usage with Redux

### ISSUE THREAD

**Issue by elzii** [krakenjs/zoid#126]
I'm getting a little tripped up trying use xcomponent when building a library (using React) that has a single UMD export.

I would like to return the store, or at least the `dispatch`, to wherever the initial function is called in the parent frame.

However, I don't know if I can send the down down through xprops to the iframe (it comes in as a zalgo promise rather than a plain object) or if this is an anti-pattern.

Where is it recommended to create the store with this pattern?

Any help is appreciated!

**Comment by bluepnume** [comment]
Can you clarify -- are you trying to share the entire redux store between the parent page and the child frame?

Who owns the original store in this case -- the parent or the child?

**Comment by elzii** [comment]
@bluepnume Whatever works, honestly. I would prefer it to be created in the child, but I'm wondering the best way to pass it up to the parent. For example:


## In parent window
```js
const myWidget = myLibrary.init('#container', { /* some config options */ })
```

## myLibrary.js
```js
export const init = (selector, config) => 
  const store = configureStore(config)
  
  ReactDOM.render(
    <Provider store={store}>
      <MyReactXComponent />  
    </Provider>,
     selector
  )
```

I recognize that this may not be correct - it leads to trouble trying to use `connect` for components within `MyXComponent` as the store a promise and not an object at first.

I'll set up an isolated project if it helps to debug.

**Comment by bluepnume** [comment]
So -- you'll have to forgive me because my experience with Redux is slightly limited, but could you do something like this?

### Parent

```javascript
MyComponent.render({
    setupReduxSubscribers({ subscribe, dispatch, getState }) {
        
        subscribe(() => {
            getState().then(state => {
                console.log('State:', state)
            });
        });

        dispatch({ type: 'INCREMENT' });
    }
});
```

### Child

```javascript
let store = createStore(myReducer);

window.xprops.setupReduxSubscribers({
    subscribe: (handler) => { store.subscribe(handler) },
    dispatch: (obj) => { store.dispatch(obj) },
    getState: () => { return store.getState(); }
});
```

This way we create the store on the child, and pass up the methods we need from the store to be called by the parent. Then the parent can subscribe, dispatch, getState, or whatever else you need.

**Comment by bluepnume** [comment]
Any luck with the above?
