### ISSUE TITLE
Allow vh/vw units when setting dimensions in xcomponent definition

### ISSUE THREAD

**Issue by pinkhominid** [krakenjs/zoid#127]
Currently the code throws
`Uncaught Error: Expected options.dimensions.height to be a px or % string value`

**Comment by bluepnume** [comment]
Hi @pinkhominid -- sure, I can consider this, but for now one possibility is for you to override the `containerTemplate` in your component.

The default is this: https://github.com/krakenjs/xcomponent/blob/master/src/component/component/templates/container.jsx

You can change

```css
width: ${ width };
height: ${ height };
```

to 

```
```css
width: 100vw;
height: 100vh;
```

**Comment by pinkhominid** [comment]
Thanks @bluepnume. Will try that. Great lib!
