### ISSUE TITLE
autoResize problems when width is activated

### ISSUE THREAD

**Issue by namirsab** [krakenjs/zoid#129]
### Observed Behaviour
When setting `autoResize: { width: true }`, the iframe resizes whenever the content size is bigger than the `xcomponent-outlet` div. On the other side, the iframe **will not resize** when the window is resized (or in a mobile device, when the orentation changes and the window is resized)

### Expected behaviour
* The `xcomponent-outlet` listens also to window size changes, not only to internal size changes.

### Background info
`xcomponent`  attaches absolute width and height attributes to that div. 
![image](https://user-images.githubusercontent.com/6980777/32050830-8940da74-ba52-11e7-8d64-51876b2ac265.png)

This is updated whenever the iframe content is changed, but not if the window is resized.
@bluepnume

**Comment by bluepnume** [comment]
Hi @namirsab -- thanks for the report! Out of interest, what do you currently have `dimensions` set to?

**Comment by namirsab** [comment]
It's set to 100%

**Comment by namirsab** [comment]
I think I had it to 100%. I can't confirm it now because

**Comment by namirsab** [comment]
I think I had it to 100%. I can't confirm it now because

**Comment by lukepuraSPR** [comment]
@namirsab Did you ever figure out a solution for this issue? Experiencing the same problem.

**Comment by sprsam** [comment]
Our solution ended up being related to removing autoResize: true for both height and width. `autoResize: { height: true, width: false }`. As a result, our width: 100% dimension setting stuck around while post robot helped relay the new height.
