### ISSUE TITLE
Edge browser - The popup not being brought to front when clicking the overlay

### ISSUE THREAD

**Issue by ghost** [krakenjs/zoid#137]
Hi @bluepnume,

There is one issue with the popup on Microsoft Edge.

Steps to reproduce:

1. Open https://developer.paypal.com/demo/checkout/#/pattern/client in Microsoft Edge
2. Open the popup by clicking the Paypal Checkout button
3. Click the overlay, the popup will go background
4. Click the overlay again, the popup is not brought back to front. Expected: the popup should be brought back to front.
5. However, after I resize the parent window, clicking on the overlay will bring the popup to front!

Tested on Microsoft Edge 40.15063.0.0 , Microsoft EdgeHTML 15.15063 on Windows 10 Enterprise.

Thanks,
Ky

**Comment by kms-ky-truong** [comment]
Hi again,

Looks like this is an issue of Microsoft Edge. Please see:

- https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/6274497/
- https://connect.microsoft.com/IE/feedback/details/2236027/microsoft-edge-bug-report-javascript-window-focus

FYI - The latest version of Microsoft Edge (Microsoft Edge 41.16299.15.0, Microsoft EdgeHTML 16.16299) works differently, ie: when clicking the overlay, the popup goes to background and goes back to front in the blink of an eye. That's how it works on IE 11.

Is it possible to make it works consistently on every Edge versions (same as the latest version)?

Thanks,
Ky

**Comment by bluepnume** [comment]
If you're still seeing this issue, please raise an issue over on the paypal repo.
