### ISSUE TITLE
React + xprops lifecycle (and possibly hot loader?)

### ISSUE THREAD

**Issue by meza** [krakenjs/zoid#138]
We're trying to get xcomponent working for our project, but got stuck at being able to read the `window.xprops` in our component's render. When the loaded in component render function fires, the xprops variable is not yet populated.

The `<MyComponent {...window.xprops}>` method which is suggested everywhere seems to leave us with an undefined object, but a `setTimeout(function(){console.log(window.xprops)},500);` does seem to have all the passed in props.

Any pointers would be much appreciated.

We are using React Hot Loader which _could_ be the issue, although I'm not certain

**Comment by bluepnume** [comment]
Interesting. Are you loading the xcomponent definition in a script tag before you load your react component?

**Comment by meza** [comment]
Yes, the host app has no react at all. The xcomponent definition is bundled together with the xcomponent lib, and we load that.

**Comment by bluepnume** [comment]
Sure -- but I meant in the iframe -- are you loading xcomponent and the definition _before_ you try to access `window.xprops`?
