### ISSUE TITLE
Implementation of Child Resize Callback

### ISSUE THREAD

**Issue by IvoPereira** [krakenjs/zoid#141]
Hello,

I am using a component with autoResize enabled, that displays a modal that occupies whole screen after clicking on a button.

Currently I am facing an issue that is that the modal has a backdrop, and as soon as you click the button and the Modal and its backdrop appears, the child haven't had time yet to be resized, so we are able to see the backdrop being resized from a square to full-screen dimensions.

Perhaps having a callback or being able to specify an event listener on that, would allow me to only open the modal once the iframe was totally resized.

**My current implementation:**
```js
handleModalToggle: function() {

      if (typeof window.xchild !== 'undefined') {
        const width = this.state.modal.isOpen ? '100px' : '100%';
        const height = this.state.modal.isOpen ? '100px' : '100%';

        window.xchild.resize(width, height);
      }

      this.setState(update(this.state, {
        modal: {
          isOpen: {
              $set: !this.state.modal.isOpen
          }
        }
      }));
    },
```

It would be great If I could just pass a callback to window.xchild.resize, so that the modal would be open once the resize is complete.

Or somehow be listening for a resize in the child window to trigger it.

Any ideas on how to achieve this?

**Comment by bluepnume** [comment]
Can you use `window.xchild.resize(width, height).then(handler => { ... })`?

**Comment by muhaimincs** [comment]
how exactly to run it? I am not aware xchild beside xprops

**Comment by bluepnume** [comment]
You can now use:

```
window.xprops.resize(width, height).then(handler => { ... })
```
