### ISSUE TITLE
Mutation Deprecated

### ISSUE THREAD

**Issue by katerberg** [krakenjs/zoid#151]
Hello, when using xComponent.create(), I am getting the following warning in Firefox Quantum:
`Use of Mutation Events is deprecated. Use MutationObserver instead`

Please let me know if you need an example to help triage.

Thanks!

**Comment by bluepnume** [comment]
This should be fixed, please let me know if you still see it.

**Comment by christianpv** [comment]
The warning is still there when using the latest minor of version 6 of the library. I tracked it down to the event `DOMNodeInserted`. Would you like me to submit a PR?

**Comment by katerberg** [comment]
@christianpv I'd create a new issue or PR and link it to this one. Most maintainers don't check closed issues.
