### ISSUE TITLE
Iframe source downgraded to http

### ISSUE THREAD

**Issue by dziamid** [krakenjs/zoid#157]
I've set a URL that points to an https in my xcomponent definition:

```
const component = xcomponent.create({
  tag: 'customer-widget',
  url: `https://dvelp-support-client-dev.herokuapp.com/customer/`,
  ...
});
```

I'm getting this error:

> (index):1 Mixed Content: The page at 'https://love-island-jzgfnnjiwu.now.sh/' was loaded over HTTPS, but requested an insecure resource 'http://dvelp-support-client-dev.herokuapp.com/customer/?uid=ffa8ca2c7a&logLevel=info&version=latest&xcomponent=1'. This request has been blocked; the content must be served over HTTPS.

As you can see, the URL has downgraded to _http_ and not loading due to mixed content policy. 

Please, see repro here:  https://love-island-jzgfnnjiwu.now.sh/

**Comment by dackmin** [comment]
The repro url is working fine, did you find out what the issue was ?

**Comment by dziamid** [comment]
Yeah, the issue happened when I set env var XCOMPONENT_FRAME_ONLY, otherwise all works great
