### ISSUE TITLE
Minified package is 50kb heavier between 6.0.50 & 6.0.60

### ISSUE THREAD

**Issue by dackmin** [krakenjs/zoid#158]
Hi guys,

`xcomponent` seems to have gained around 50kb between versions `6.0.50` & `6.0.60`, and I can't find the direct cause of this sudden weight gain, except maybe [this commit](https://github.com/krakenjs/xcomponent/commit/4a87859b75a76dca9e20e371859e57674590b6d8).

I primarily used `xcomponent` to have a minimum sized umd module that will bring its heavy frames friends, but 206kb of non-shakable minified bundle is wayyyy too much to be considered usable 😢.

If the ~50kbs are due to the use of [grumbler](https://github.com/krakenjs/grumbler), will it be possible to keep a branch without it ? I don't really care having to install from a custom branch if it saves 50kb in the process.

Thanks a lot !

<img width="593" alt="capture d ecran 2018-05-22 a 09 11 12" src="https://user-images.githubusercontent.com/1873323/40348063-b56f1b9e-5da2-11e8-996e-d7dafacf0e3b.png">

**Comment by bluepnume** [comment]
Great catch. I've made a fix and published. Please note that this package is now called `zoid`, so you'll need to update your package.json, and your code from `xcomponent.create()` to `zoid.create()`.
