### ISSUE TITLE
Functions returning Promises even with promisify: false

### ISSUE THREAD

**Issue by MrToph** [krakenjs/zoid#159]
Hi,
I was surprised that all functions passed as `props` seem to return (Zalgo)Promises that resolve to the actual value returned, no matter if the function is defined as `async` or not.
I haven't found anything about it in the documentation.

There is a `promisify: false` flag in the docs, but it doesn't seem to work for me, the function still returns a Promise.

Is there a way to make the functions return the plain value?

**Comment by bluepnume** [comment]
Yep, that's expected -- functions depend on sending messages between frames, which is asynchronous by default. So there's no way to return the raw value, it has to be an asynchronous response. Promises made the most sense for this.

For more detail, please see https://medium.com/@bluepnume/introducing-post-robot-smart-cross-domain-messaging-from-paypal-bebf27c8619e -- this is the library we use for all cross-frame communication.
