### ISSUE TITLE
prerenderTemplate isn't working as expected

### ISSUE THREAD

**Issue by ar7casper** [krakenjs/zoid#160]
My component defintion - 

```
const HostedComponent = xcomponent.create({
  tag: 'xcomponent-testing',
  url: {
    development: 'http://localhost:8081/testing',
  },
  dimensions: {
    width: '100%',
    height: '100%'
  },
  prerenderTemplate (opts) {
    console.log('____opts', opts);
    const { jsxDom } = opts;
    return jsxDom('div', null, 'PLEASE');
  }
})
```

### Expectation 
I'm expecting to see two iframes, and a transition between them.
### Result
Only the `xcomponent-component-frame` is showing up. 

#### What I've tried -
- The `console.log()` is being printed out. 
- I've tested the `opts.jsxDom('div', null, 'hello world')` on the console, it works. 
- Playing around with syntax (arrow functions, etc.)
- tried vanilla JS: 
```
const loader = opts.document.create('div');
loader.innerHTML = 'Loading';
return loader;
```
- Tried adding the `componentTemplate`

I feel a bit lost.

On that matter, is there a way to 'know' whether the iframe has been loaded?
Was thinking of adding the loader in Angular (the host) and listen for an update saying 'iframe is ready to show' and do the switching on Angular. 
I can pass in a prop called `onRender` that will be fired on `componentDidMount` or something, but is there an api I could use for that?
Could that be achieved?

**Comment by bluepnume** [comment]
Found the problem. You need to make sure the prerenderTemplate is wrapped in an `html` element:

```
  prerenderTemplate (opts) {
    console.log('____opts', opts);
    const { jsxDom } = opts;
    return jsxDom('html', null,
        jsxDom('body', null,
            jsxDom('html', null, 'PLEASE')
        )
    );
  }
```

> On that matter, is there a way to 'know' whether the iframe has been loaded?

You can do:

```
FooComponent.render({ ... }, '#foo').then(() => {
    console.log('Component is loaded');
});
```

Alternatively you can pass an `onEnter` prop when you render the component.

**Comment by timh770773** [comment]
Just ran into this. This should probably be added to the API docs... in the docs currently it looks like example just calls for adding a div without enclosing it in an html tag.
