### ISSUE TITLE
Semantically version the package

### ISSUE THREAD

**Issue by pinkhominid** [krakenjs/zoid#161]
I really like this library and use it at work. In hopes of decreasing the risks going forward, I'm going to bring up this issue.

The rename should have been a major version release. Folks who float the version, e.g. ^6.x.x, were potentially zinged by the file name changes.

Thanks and keep up the great work!

**Comment by bluepnume** [comment]
People still using the xcomponent package name shouldn't have automatically gotten any breaking changes, right?

**Comment by pinkhominid** [comment]
Yeah mostly, except people still consuming it from bower :/

$ bower info xcomponent
bower not-cached    https://github.com/krakenjs/xcomponent.git#*
bower resolve       https://github.com/krakenjs/xcomponent.git#*
bower download      https://github.com/krakenjs/xcomponent/archive/v6.0.63.tar.gz
bower extract       xcomponent#* archive.tar.gz
bower resolved      https://github.com/krakenjs/xcomponent.git#6.0.63

{
  name: 'xcomponent',
  homepage: 'https://github.com/krakenjs/xcomponent',
  version: '6.0.63'
}

**Comment by yoshprogrammer** [comment]
Agreed, was investigating the use of this for work and as of now, I am actually sidelining the framework. Major changes like this without any semantic versioning or notice is rather concerning.

**Comment by bluepnume** [comment]
I hear you both - but Bower is a deprecated platform, and xcomponent/zoid doesn't even have a Bower.json. This repo isn't officially set up to support Bower, and npm users will not see any backwards incompatible or breaking changes.

**Comment by pinkhominid** [comment]
@bluepnume, fair enough on Bower. Though I think that the larger point is that most popular libs follow semantic versioning and it helps decrease risks. I know it's gray here whether the rename was a "breaking change", since you started publishing under a different name.  My interest here is in hearing your stance on whether the library follows semantic versioning or not so I can plan accordingly.

**Comment by bluepnume** [comment]
Yep, for sure -- we absolutely do follow semver. Just in this case the feeling was the name change mitigated the lack of a major version bump.
