### ISSUE TITLE
Updating Child Props

### ISSUE THREAD

**Issue by ar7casper** [krakenjs/zoid#162]
Hi,

I'm going over the documentation and I can't find a native way of updating the child's props.

For instance, my parent has a Dark mode toggle.
I'd like to change the child's theming on change.

Managed to find __postRobot__ var in my frame, just wanna make sure that's the way of doing it and how.

**Comment by bluepnume** [comment]
You should be able to do something along the lines of:

```javascript
MyComponent.render({ ... }, '#foo')
    .then(component => {
        // when toggle is selected
        component.updateProps({ ... });
    });
```

Then in the child frame:

```
window.xchild.onProps(props => {
    // toggle the style
});
```

**Comment by edwardchanjw** [comment]
It worked well. Could you provided how to use for post-robot on this usage or how to call updateProps in React-end-to-end example. Actually i interested more on Vue.

It could help userland to setup Redux, as the concept is just observe the setter/vaue in Parent iframe, then change the props, then have Children iframe to observe the setter/value in props, as iFrame does not share variables. The props/state messaging is crucial sample might ease the implementation.

**Comment by chemoish** [comment]
I am still looking through the source code to figure out how things are wired up. Is there a recommendation for React driver?

I am guessing `MyComponent.render` is abstracted by the driver.

**Comment by alexkaduk** [comment]
@chemoish Have you found how pass updated props for React?

**Comment by chemoish** [comment]
@alexkaduk I did, but I had to reverse engineer code and examples (Probably had to duplicate code from the driver).

Unfortunately don't have the example anymore, I am no longer working on this.

**Comment by pablit07** [comment]
I got this to work for the React driver by re-rendering the child component in window.xprops.onProps. (Note that window.xchild has been removed)

In my index.html, in addition to my existing render call, I do
`window.xprops.onProps(props => /* paste render code here */ )`

Is there some way the driver could be made to handle this?

**Comment by bluepnume** [comment]
> Is there some way the driver could be made to handle this?

Perhaps yes. Right now drivers only really apply to the parent page though, the assumption is that the child window could be any framework (or no framework). So `onProps` is a generic way to listen for prop changes.

Please feel free to open up a new issue to discuss.

**Comment by mayteio** [comment]
For react specifically, you can use the following hook in your child to enjoy up-to-date props:

```typescript
// hook
export function useZoidProps<T>():T{
  const [props, set] = useState();
  window.xprops.onProps(set);
  return props || {};
}

// usage
type Props = {
  prop1: string|undefined
  prop2: number|undefined
}

const {prop1, prop2} = useZoidProps<Props>();
```

**Comment by satyamTheSong** [comment]
> I got this to work for the React driver by re-rendering the child component in window.xprops.onProps. (Note that window.xchild has been replaced)
> 
> In my index.html, in addition to my existing render call, I do `window.xprops.onProps(props => /* paste render code here */ )`
> 
> Is there some way the driver could be made to handle this?

Hi can you please share an example, I don't understand what do you mean by re-rendering the child component? do we not need to call updateProps with react?

**Comment by satyamTheSong** [comment]
> It worked well @bluepnume . Could you provided how to use for post-robot on this usage or how to call updateProps in React-end-to-end example. Actually i interested more on Vue.
> 
> It could help userland to setup Redux, as the concept is just observe(not observe but achieve mostly similar) the setter/vaue in Parent iframe, then change the props, then have Children iframe to observe the setter/value in props, as iFrame does not share variables. The props/state messaging is crucial sample might ease the implementation, at least straightforward from parent iFrame

Hi, it might be a long shot, but did you get this sorted? is there any way in react from where we can call updateProps?

**Comment by ericlhopper** [comment]
Hi,

I'm going over the documentation and I can't find a native way of updating the child's props in React.

In this trimmed down example of my parent component, updateProps is undefined. I'm not sure I'm going down the right path...
`import React, { useEffect } from 'react';

import AuthComponent from '../../AuthComponent';
import ReactDOM from 'react-dom';
var MyReactAuthComponent = AuthComponent.driver('react', {React, ReactDOM});

function demoParent(props) {

  useEffect(() => {
    if (MyReactAuthComponent?.updateProps) {
      console.debug(`SignInFido: useEffect() calling MyReactAuthComponent.updateProps`);
      MyReactAuthComponent.updateProps({email: props?.email});
    } else {
      console.warn(`SignInFido: useEffect() MyReactAuthComponent?.updateProps is undefined`);
    }
  }, [props?.email]);

  const handleLoginByZoidComponent = async () => { 
  };

  const renderContent = () => {
    return  <MyReactAuthComponent
              email={props?.email}
              buttonText='Zoid Button'
              onClick={handleLoginByZoidComponent}
            ></MyReactAuthComponent>
  };

  return (
    <React.Fragment>
      { renderContent() }
    </React.Fragment>
  );
}

export default demoParent;`

**Comment by ericlhopper** [comment]
I found the answer in the advanced/react-end-to-end demo. I didn't need to do anything from the parent. I simply added the following function to the child zoid component:

```
function useXProps() {
  const [xprops, setXProps] = React.useState(window.xprops);
  React.useEffect(() => {
    window.xprops.onProps((props) => {
      setXProps({ ...props });
    });
  }, []);
  return xprops;
}

function App(props) {
  const { disabled, buttonText } = useXProps();
  . . .
```

**Comment by KozakoPolako** [comment]
Props wrapper for vue2.7 + / vue 3:
```ts
import { computed, ref } from "vue"
export function useZoidProps() {
  const props = ref<ZoidProps>(window.xprops)
  
  window.xprops.onProps((newPropsValue) => {
    props.value = newPropsValue
  })
  //optional v-model wrapper (when used with vue 2 host app props name and event: value | onInput )
  const model = computed({
    get() {
      return props.value.modelValue
    },
    set(val: string) {
      props.value["onUpdate:modelValue"](val)
    },
  })
 
  return { zoidProps: props, zoidModel: model }
}


type ZoidProps = {
  modelValue: string
  "onUpdate:modelValue": (val: string) => void
}
```
Usage: 
```vue
...
    <v-main>
      {{ zoidProps.modelValue }}
      <v-text-field v-model="zoidModel"></v-text-field>
    </v-main>
  </v-app>
</template>

<script lang="ts">
import { defineComponent } from "vue"
import { useZoidProps } from "@/zoidCreate"

export default defineComponent({
  setup() {
    const { zoidProps, zoidModel } = useZoidProps()
    return { zoidProps, zoidModel }
  },
  name: "App",
  components: {},
})
</script>
...
```
