### ISSUE TITLE
Minified distribution files no longer present

### ISSUE THREAD

**Issue by joe90joe40** [krakenjs/zoid#169]
Why have you introduced this breaking change on a patch version from tags 6.0.63 to 6.0.64 by removing zoid.min.js. and others.
We depend on the minified zoid.min.js and we use this to import as a script tag.

**Comment by bluepnume** [comment]
Hi @joe90joe40 -- sorry about that. Looks like there was a problem during the last build/publish cycle. I've republished and included that file again. Apologies for the inconvenience.
