### ISSUE TITLE
How to resize Iframe after using containerTemplate, or is it DIMENSION not override DEFAULT_DIMENSIONS for containerTemplate

### ISSUE THREAD

**Issue by edwardchanjw** [krakenjs/zoid#171]
Hi, The project is quite big but stable, and the winning is seamless embed different components framework.

Let say, I want to put the props advanced example in absolute position using containerTemplate. Furthermore, would like to dynamic resize it(Even though i have no clue how to do it....sorry if i am provide bad code). For now, i manually set the size to be larger in demo/common/Login.css and props/Login.js. The Iframe still in 300 x 150, even others div in the tree is resize to 600x600, so the iFrame actually crop half. (constants.DEFAULT_DIMENSIONS is 300x150.)

Consider [Like Floating Poker Star Ads](https://i.ytimg.com/vi/2db2uzayDnA/maxresdefault.jpg)
Actually think about this image, it should be great if some of the ads internet company can collaborate on this project as Ads always require using iFrame. (Consider the use case on iFrame is more on Ads and third party components on Platform/CMS such as Attlassian, Github App, Wordpress etc, that allow rendering on the allowed areas)

**Login.js**

```
    containerTemplate: function containerTemplate(opts,on) {
        var newDiv = opts.document.createElement("div"); 
        newDiv.style.cssText = 'position:absolute;top:100px;left:100px;';
        newDiv.id = opts.id
        opts.dimensions= {
            width: '600px',
            height: '600px'
        },
        opts.outlet.cssText = 'width:600px;height:600px;'
        newDiv.appendChild(opts.outlet);

        return newDiv;
    },
    
    dimensions: {
        width: '600px',
        height: '600px'
    },
    autoSize: {height: true, width:true}
``` 

**Login.css**

```
body {
    text-align: center;
    border: 1px solid #ccc;
    height: 600px;
    width: 600px;
}
```

**Comment by twig-openlearning** [comment]
i'm guessing it has something to do with `opts.on()` but without up to date docs it's quite difficult to figure out

**Comment by bluepnume** [comment]
See https://github.com/krakenjs/zoid/blob/master/docs/api.md#autoresize--height-boolean-width-boolean-element-string-

**Comment by twig-openlearning** [comment]
is there a way to listen in for that change event?

we're trying to remove all inline css from elements to attain a WCAG AA rating for accessibility and this is one of the common offenders

https://www.nomensa.com/blog/2011/css-inline-styles-and-why-they-are-considered-harmful-accessibility

**Comment by twig-openlearning** [comment]
Our approach is fairly simple. In `containerTemplate`:

* create a `style` element
* fill it in with the css from https://github.com/krakenjs/zoid/blob/master/src/component/templates/container.jsx
* append it into `document.head` (optionally with a variant of the zoid id so we can update/remove it when needed)

And thanks for linking the docs

**Comment by twig-openlearning** [comment]
> neither approach really introduces any real accessibility issues

I agree with ya, but hitting that WCAG AA rating means following a lot of stuff to spec even if it feels like overkill.

Would it be too much to ask to make an `onResize` prop a first class citizen in zoid? I mean the groundwork is already there, you'd just need to add an extra call to a prop so we could hook into that event. It would be rather tedious for us to duplicate it every time we used zoid

**Comment by twig-openlearning** [comment]
Ahh, that makes a lot of sense.
Thanks for clarifying that!

**Comment by muhaimincs** [comment]
hi @twig-openlearning could you share do you trigger the size?

**Comment by twig-openlearning** [comment]
zoid was making our lives difficult for the benefits it brings, so we ended up writing our own iframe implementation with plans to migrate to https://github.com/ryanseddon/react-frame-component in the near future

**Comment by muhaimincs** [comment]
did you bundle Reactjs and share on client?

**Comment by twig-openlearning** [comment]
If you mean by using webpack to compile to js bundles then yes
