### ISSUE TITLE
renderTo() broken in Chrome 67

### ISSUE THREAD

**Issue by Magneticmagnum** [krakenjs/zoid#174]
It seems that `renderTo()` functionality is broken in Chrome 67.

**Steps to reproduce:**
1. Load the demo from `demo/advanced/remote/index.htm`
2. Click on `OPEN LOG IN`
3. Check your console for the error: `Uncaught Error: Unable to find window by ref` and notice spinner will spin indeterminately.

File of concern is in `line 11` `login-button.htm`: `            MyLoginZoidComponent.renderTo(window.parent ...`

**BROKEN in**

- Chrome: 67.0.3396.99

**Works in the following browsers**
- IE: 11.165.17134.0
- Firefox: 61.0.1 (64-bit)
- Edge: Microsoft Edge 42.17134.1.0

**Comment by Magneticmagnum** [comment]
So, it seems to be something with how chrome handles loading iframes from the local filesystem / file domain.

If i host these files on a server with something like `http-server` (https://www.npmjs.com/package/http-server), it works!

**Comment by bluepnume** [comment]
Perfect. Yep, local file system messes with cross-domain comms.
