### ISSUE TITLE
handle load error 

### ISSUE THREAD

**Issue by nishantgupta2501** [krakenjs/zoid#175]
timeout and OnError is not working for me, my component definition is
window.MyChatComponent = zoid.create({
// The html tag used to render my component
tag: 'my-chat-component',
// The url that will be loaded in the iframe or popup, when someone includes my component on their page
url: defaults.babbleUrl,
autoResize: {
height: true,
element: '.minimized-chat',
},
dimensions: defaults.dimensions,
timeout: 6000,
onError: defaults.chatOutageCallBack
});
first of all above definition doesn't set the properties and when i manually set the timeout and onError at runtime, even then it doesn't call the onError function.
Am i doing something wrong? basically i just want to display a custom error message when my url is not resolved or down

I am referring to one of old issue 

[https://github.com/krakenjs/zoid/issues/85](url)

**Comment by bluepnume** [comment]
Please pass `onError` when you render the component, not when you create it.
