### ISSUE TITLE
Move iframe to other node will cause no handler found

### ISSUE THREAD

**Issue by lustan3216** [krakenjs/zoid#178]
First, thanks for your amazing plugin.

Due to some customize reasons, I need to build popup mode myself. I meet a problem is will get `no handler found` error when trying to move the iframe to another node.

The scenario is I need to fetch a data like `popup` or `inline` from the child iframe, and pass to parent domain to move the iframe to under another node. So at this moment, I need to use `document.querySelector('anothor node').replaceWith(xComponent)`.

Once it trigger is will invoke this error.

<img width="1670" alt="screen shot 2018-09-05 at 11 45 51 am" src="https://user-images.githubusercontent.com/12712127/45066487-006d1580-b102-11e8-8a97-3e5d356291f5.png">

Might you give me some advice or workaround? thanks a lot

**Comment by bluepnume** [comment]
There is no known fix for this at the moment. Moving an iframe closes and re-opens the inner window, which wreaks havoc with zoid's listeners.
