### ISSUE TITLE
React: height 100% of child content, without scrolling

### ISSUE THREAD

**Issue by petrgazarov** [krakenjs/zoid#181]
Hi there!

Thank you for the library. I am trying to make it work with React and would like to have
- no scrolling
- iframe has 100% of the height of the content of the child

I did not have luck with `autoResize` option, perhaps I'm missing something obvious.

I tried a few ways, these did not work:
1) 
```
  dimensions: {
    width: '100%',
    height: '100%',
  },
  autoResize: true
```
Every time I include `autoResize: true`, I get weird bug where the height of the iframe keeps growing by thousands of pixels per second and never stops well into millions

2) 
```
  dimensions: {
    width: '100%',
    height: '100%',
  },
  scrolling: false
```
This just renders the iframe to 100% of the parent (and not the child), and cuts of the rest of the child content below that line (since there is no scrolling)

This worked, somewhat:
```
  dimensions: {
    width: '100%',
    height: '1000px',
  },
  scrolling: true
```
I say somewhat because I get two scollbars (one for the child and one for the parent), and, at least in Chrome, it results in an awkward scrolling behavior.

What would be great is a way to have one scrollbar, while the iframe renders to the 100% height of the child. Do you have ideas about what I should try in order to achieve this result?

In other respects, I follow docs example to set up the Zoid and React components. I'm using
```
react@16.5.0
zoid@^7.0.7
```

Thanks!

**Comment by kidequinox** [comment]
@petrgazarov have you made any progress on this issue ?

**Comment by petrgazarov** [comment]
@kidequinox Nope

**Comment by kidequinox** [comment]
@petrgazarov, try:

```
autoResize: {
  width: false,
  height: true
},
```

This works on my end, but height is never really 100%, its like 98% and still triggers a scrollbar. I'm working through this to see if I can get it all smooth.

**Comment by muhaimincs** [comment]
how do you serve your child component? load `<script> tag?

**Comment by corepay** [comment]
I'm not a good developer at all so this may be way off - but I did something similar with a vanilla iFrame on a long-scroll page setting the CSS props of the `<iFrame>` in the parent

```
position: absolute;
height: 100%;
width: 100%;
top: 0,
left: 0
` ``

**Comment by mrudult** [comment]
We tried [this](https://github.com/krakenjs/zoid/issues/347#issuecomment-860094338) in one of our projects and it is working fine for us till now.
