### ISSUE TITLE
React: Display iframe external URL

### ISSUE THREAD

**Issue by zicbreeze** [krakenjs/zoid#182]
Hi 
I'm trying to display external URL in iframe by using React as https://medium.com/@bluepnume/creating-a-cross-domain-react-component-with-xcomponent-fbcccc4778fd
Is this possible to do?

I got errors.
1.Element type is invalid: -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
2.Uncaught Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development.

**This is my test react code.**
`import React from "react";
import ReactDOM from "react-dom";
import "./index.css";
import zoid from "zoid";

let ZoidComponent = zoid.create({
  // The html tag used to render my component
  tag: "test-component",
  url: "https://www.google.com"
});

ReactDOM.render(<ZoidComponent />, document.getElementById("root"));
`

**Comment by softpot9** [comment]
Hi @zicbreeze 
I have same issue now. how to figure out this problem? Please help me. Thanks.

**Comment by davchee** [comment]
Was this issue resolved , can you show the solution or reopen this issue please?
