### ISSUE TITLE
npm test fails due commands not being in path

### ISSUE THREAD

**Issue by erikh2000** [krakenjs/zoid#183]
I followed the instructions from https://github.com/krakenjs/zoid/blob/master/CONTRIBUTING.md Everything completed with no errors up to the point that I reached "npm test".

Running `npm test`, results in: `sh: eslint: command not found`.

Are you expecting it to be installed globally? I added `npx` in front of the `eslint` call in package.json to get past that.

Then the same `command not found` error appeared  for flow-typed. I added `npx` in front of `flow-typed` to get past that.

After those two fixes, there are errors related to missing definitions for `beforeEach`, `afterEach` in the tests.

I feel like I've missed some single thing in the project setup that would probably resolve all these problems at once. But out of the box, following the directions, I'm unable to get "npm test" to run.

**Comment by bluepnume** [comment]
Very strange. Out of interest:

- What version of npm are you using?
- What do you see for `npm ls eslint`
