### ISSUE TITLE
Will redirects break the xcomponent connection?

### ISSUE THREAD

**Issue by ziyadparekh** [krakenjs/zoid#187]
Say my parent page is A and my child pop-up or iframe is B. Initially A opens an xcomponent window and renders B. If B redirects itself to a temporary page (say some login page on a different domain) and then that login page redirects back to B, is the original connection between A and B broken or can B still communicate with A?

**Comment by bluepnume** [comment]
You should still be good to go :) so long as you load the script in the child window when you want to resume comms.
