### ISSUE TITLE
Generated source maps are empty

### ISSUE THREAD

**Issue by bendlas** [krakenjs/zoid#192]
All of the generated source map files don't actually contain any mappings:

- https://github.com/krakenjs/zoid/blob/master/dist/zoid.frame.js.map
- https://github.com/krakenjs/zoid/blob/master/dist/zoid.frame.min.js.map
- https://github.com/krakenjs/zoid/blob/master/dist/zoid.js.map
- https://github.com/krakenjs/zoid/blob/master/dist/zoid.min.js.map

I suspect, that this is actually bug in `krakenjs/grumbler-scripts`, as the same bug is in `krakenjs/post-robot` as well.

**Comment by bluepnume** [comment]
Fixed! Thanks again for letting me know.
