### ISSUE TITLE
How can I fix X-Frame-Options issue?

### ISSUE THREAD

**Issue by softpot9** [krakenjs/zoid#194]
Hi,

Here is code. Please help me. Thanks.

```
import React from "react";
import ReactDOM from "react-dom";
import zoid from "zoid";

let ZoidComponent = zoid.create({
  tag: "test-component",
  // url: "https://delivery.wholefoodsmarket.com"
  url: "https://www.walmart.com/account/login"
});

let MyLoginReactZoidComponent = ZoidComponent.driver('react', {React, ReactDOM});
class Main extends React.Component {
  constructor(props) {
      super(props);
  }
  render() {
      return (
          <div>
              <MyLoginReactZoidComponent />
          </div>
      );
  }
}
ReactDOM.render(<Main />, document.getElementById('react-root')); 
```

![image](https://user-images.githubusercontent.com/26469987/48677362-60f5e580-eb7c-11e8-8739-a3f735513985.png)

**Comment by bluepnume** [comment]
You need to set the x-frame-options header. You can only do this on sites you own; so it's unlikely you can make this work with walmart.com

**Comment by softpot9** [comment]
Hi @bluepnume , Thanks for your quick response.

Please see it. I found it in description.

"Is this different to react-frame-component?

Yes. react-frame-component allows you to render html into a sandboxed iframe on the same domain. zoid is geared around sharing functionality from one domain to another, in a cross-domain iframe."

That's why I have decided to use Zoid.

**Comment by bluepnume** [comment]
Sure. But zoid can't get around browser restrictions. At the end of the day, an iframe needs that x-frame-options header otherwise it will be blocked by the browser.

**Comment by softpot9** [comment]
Ah, so It's relation with Browser?

**Comment by bluepnume** [comment]
Yep. For security reasons, no way to get around this.
