### ISSUE TITLE
Error: Expected message to have sourceDomain

### ISSUE THREAD

**Issue by jelohe** [krakenjs/zoid#195]
After upgrading from xcomponent to zoid, my window.xprops are not populated anymore, and i'm seeing the following error in the browser console on startup:

`Error: Expected message to have sourceDomain`

I literally only installed the latest zoid version, uninstalled xcomponent and replaced the corresponding `xcomponent.create` with `zoid.create`. I have no clue what is causing that error. 

I have also noticed that when i inspect my `window.xprops`, they are now undefined, when they used to be populated.

**Comment by MatiMenich** [comment]
Having the same issue here, do you have any updates on the matter @jelohe ?

**Comment by bluepnume** [comment]
@MatiMenich -- same question to you. Do you have the latest version of post-robot running in each window/frame?

**Comment by MatiMenich** [comment]
@bluepnume yep, each frame is loading the same script, and according to my package-lock, running zoid `7.0.29` and post-robot `9.0.19`

**Comment by bluepnume** [comment]
Hmm. The zoid package no longer references the name `sourceDomain` anywhere: https://github.com/krakenjs/zoid/blob/master/dist/zoid.frame.js

So I seriously suspect some older version is appearing in one of your frames somewhere.

**Comment by MatiMenich** [comment]
You're right, after some close inspection I've noticed that the component URL was pointing to another frame that was loading a different version of my script 😓. Thank you

**Comment by bluepnume** [comment]
No prob at all! Glad it's working
