### ISSUE TITLE
Popup is opened on the wrong monitor

### ISSUE THREAD

**Issue by trainerbill** [krakenjs/zoid#199]
Looks like the getPosition function moved and I can't find it anywhere so submitting here.

zoid/src/component/window.js getPosition function is producing the wrong x occasionally.

My window.screenX is 1680, but the get position function calculates the x as 2338 which i think is pushing the popup to my middle monitor instead of right monitor in a 3 monitor setup.

Here is a screenshot from a breakpoint.

![screen shot 2018-12-27 at 2 54 37 pm](https://user-images.githubusercontent.com/3578259/50494203-6f3ee900-09e7-11e9-8165-289b7ce8710e.png)

![image](https://user-images.githubusercontent.com/3578259/50494297-1754b200-09e8-11e9-8df3-fa1d6f04a1ec.png)

Screenshot on website

<img width="592" alt="screen shot 2018-12-27 at 2 56 20 pm" src="https://user-images.githubusercontent.com/3578259/50494238-a3b2a500-09e7-11e9-80c8-e25cd9810260.png">

I have noticed this on other sites as well but I can reproduce it almost all the time here:

https://sites.grenadine.co/sites/cag-acg/en/cddw

You have to go through a long checkout process.

**Comment by mcntsh** [comment]
Duplicate: https://github.com/krakenjs/zoid/issues/170

This seems to be a [bug with chrome](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-bugs/oHtZDAKp1EU) which affects the `window.screenLeft` variable with dual-monitor setups.
