### ISSUE TITLE
Paypal button on Shopify will randomly crash due to loading speed.

### ISSUE THREAD

**Issue by lustan3216** [krakenjs/zoid#200]
Relative to https://github.com/krakenjs/zoid/issues/121
The problem was not be reproduced.
Luckily, I found a [good example which is the Paypal button fall down in Shopify store](https://teamsnabbare.myshopify.com/cart). 
Before getting in this cart page, [please add this product to the cart first](https://teamsnabbare.myshopify.com/products/crawlkurs-for-nyborjare-intensiv-3-ganger-nalsta-sthlm).

I also developed two widget on the same page. 
Might you give me a help?! I tried to find the problem in the source code but without any luck. 
Thanks.

<img width="1680" alt="screen shot 2019-01-08 at 4 15 13 pm" src="https://media.giphy.com/media/lokiWPIp3VaGZGCWy9/giphy.gif">
<img width="1646" alt="screen shot 2019-01-09 at 2 43 18 pm" src="https://user-images.githubusercontent.com/12712127/50875606-3fe39f80-141d-11e9-8236-30a9846b9fcf.png">
<img width="1680" alt="screen shot 2019-01-08 at 4 15 13 pm" src="https://user-images.githubusercontent.com/12712127/50875642-6e617a80-141d-11e9-836b-bfd63c85cee5.png">

**Comment by bluepnume** [comment]
Closing this; please raise any paypal issues against the paypal repo.

**Comment by kevinscareer21** [comment]
This was helpful. If you are looking to hide the paypal button in your checkout page on shopify. Checkout this link
[https://medium.com/@navneet_yadav/how-to-hide-the-paypal-button-from-shopify-checkout-and-cart-page-2ee94591117](url)
