### ISSUE TITLE
Error: Can not register multiple components with the same tag

### ISSUE THREAD

**Issue by kksanghi** [krakenjs/zoid#201]
Can some one help me to provide a help to get rid of this. I know in the current library there is no option to deregister the component, any help would be appreciated.

We are having single page where we are trying to load the different component at run time where tags are same for each component. We can't change the tag. Please let me know how to resolve this issue.

**Comment by bluepnume** [comment]
Can you elaborate on the use-case? Is there no way to make the tag name unique based on the use-case or even the url?
