### ISSUE TITLE
Why the buildUrl method in Component was removed since version 7?

### ISSUE THREAD

**Issue by sytong** [krakenjs/zoid#204]
I notice that since version 7, the `buildUrl` method in `Component` has been removed / replaced by the `url` option. While this looks more straightforward, this new implementation has removed the possibility of returning a ZalgoPromise<string> which was originally available in `buildUrl`.

For some reason I need to resolve the url based on a server request so without the option of returning the url inside a promise I am not sure how to proceed.

**Is is possible to share with us why the option of returning the URL as a promise has been removed?**

Also is it recommend to use version 6.x (which PayPal is still using) if I am going to build a new project?
For how long would version 6.x still be supported?

**Comment by sytong** [comment]
Thanks @bluepnume for your prompt response.

I am trying to figure out how to simulate the current PayPal checkout behavior using the latest version of the Zoid framework (PayPal is still using 6.x).

Namely, I like the way PayPal open a blank window with a prerendered spinner that is part of the component but not the part of the popup. And the content of the popup is also dynamic, so I need to create a record on the server side and then use the popup to display the new record (hence I need to append a dynamic id to the popup Url). 

I looked at the PayPal code and thought I could use the `buildUrl` method but soon I realized it was gone, hence, my original question.

Right now I sort of hack it out by introducing a new props as a query param but I `decorate` it as a Function that returns a promise. That way I could take my time to load the record id before rendering the popup content.

**Comment by bluepnume** [comment]
> Right now I sort of hack it out by introducing a new props as a query param but I decorate it as a Function that returns a promise. That way I could take my time to load the record id before rendering the popup content.

That's a good direction to go. 👍 Actually that's the exact pattern we use at PayPal for the checkout component, which needs to open immediately but load a prop asynchronously.

FWIW: We'll be releasing the latest version of the PayPal Checkout lib with zoid v8 in Feb.
