### ISSUE TITLE
focus action in ContainerTemplate failed

### ISSUE THREAD

**Issue by misokatsudon** [krakenjs/zoid#205]
I added a click handler to make a clickable background overlay.
This used to work in `8.0.4` but it no longer works in `8.0.7`.
I am not sure if this has been affected some recent changes.

My click handler looks like this:
```
  containerTemplate(opts) : HTMLElement {
    const { uid, doc, outlet, focus, close } = opts;

    const focusAction = (event : Object) : ZalgoPromise<Function> => {
      event.preventDefault();
      event.stopPropagation();

      ZalgoPromise.try(focus).catch(close);
    }

   //........
```

**Comment by bluepnume** [comment]
Is your component rendered using `render()` or `renderTo()`?

**Comment by bluepnume** [comment]
Assuming it's `renderTo()`. I just pushed out a new version which should fix this. Can you please try?

**Comment by misokatsudon** [comment]
Yes `focus` is working fine now.
Thanks!!
