### ISSUE TITLE
Any recommended way to perform some actions right before Popup is about to close?

### ISSUE THREAD

**Issue by sytong** [krakenjs/zoid#206]
I am trying to display a message on the Container overlay right before the Popup is about to close (either the user closes the Popup window directly or clicks on a `close` button on the Overlay).

I don't know what is the recommended way in version 8.
(In version 6, there is a `on` function where we could use it to intercept `EVENT.CLOSE`).

I tried to add an `unload` event listener in the Overlay itself using vanilla JS but I couldn't see the desired effects as the Overlay get closed right away.

Should I `decorate` the `onClose` props of the Popup to add this effect (seems odd)?
Or is there other event hooks that I have missed?

**Comment by bluepnume** [comment]
`on` was kind of a sore-thumb in zoid 6, and was only really used to help with auto-resizing. It's been removed in the current version and replaced with a better version of `autoResize`.

As for your question: here's a kind of roundabout way of doing it by adding onClose handlers from the container template, that eventually get called:

https://github.com/paypal/paypal-checkout/blob/v5/src/checkout/template/containerTemplate.jsx#L51-L56
https://github.com/paypal/paypal-checkout/blob/v5/src/checkout/component.js#L260-L269
https://github.com/paypal/paypal-checkout/blob/v5/src/checkout/component.js#L243

onClose will then wait for any promises returned to it before closing the component.

In the next version, which I'm testing out now, zoid will have something like:

```
event.on(EVENT.CLOSE, () => {
    // return any promises here
});
```

It'll be callable directly from within containerTemplate so should make this kind of thing easier. One big shortfall of zoid right now is it's pretty difficult for container and prerender templates to react to things like you're hoping to do.

**Comment by sytong** [comment]
Wow this is fast @bluepnume 
Thanks for the update.

I will see if I can figure out the "roundabout way" for now and look forward to the next version.

**Comment by sytong** [comment]
@bluepnume I saw that PayPal has been upgraded to Zoid 9 but those onClose and onDisplay handlers are still there. So are they still required even though we can now use `event.on(EVENT.CLOSE, {} => {})`?

**Comment by bluepnume** [comment]
Internally `onClose` and `onDisplay` are now using `event.on()`. So feel free to use `event.on` if you're listening from a parent template 👍
