### ISSUE TITLE
IE11, SCRIPT5022: No ack for postMessage postrobot_method in http://localhost:8080 in 2000ms

### ISSUE THREAD

**Issue by zsakmany** [krakenjs/zoid#207]
We experience this error in IE11. It works for chrome. It is probably an issue on our site, but I'd like to ask for some tips.
```
zoid.create({
    autoResize: true,
    containerTemplate,
    defaultLogLevel: 'error',
    dimensions: {
      height: '100%',
      width: '100%',
    },
    props: propDefinition,
    scrolling: false,
    tag: 'fan-wallet',
    url: Config.url,
  });
```
The application loads, but after timeout, it throws this error multiple times (x16). What we have fond:
- If we omit `autoResize` or set it to false, we get fewer errors, but it is not working properly.
- If we increase the `ACK_TIMEOUT` to 3 sec it works properly.

We have trouble to track what part of the code runs slow and causes the timeout. The performance function in IE Devtools basically does not work. Any tip, that we should check?

**UPDATE:**
I found the bug, and a workaround. We set around ~13 of functions on `xprops`. Chrome has no problem with that, but IE struggles with all the serializations and times out.
Our workaround is to call the setter async, and it works. However is there any way you could release a new patch version for 6.x where you expose the `ACK_TIMEOUT`?

**Comment by bluepnume** [comment]
In the latest version of zoid, post-robot increases the ack_timeout if it already knows post-robot is loaded in the other window. Can you try the latest and let me know if you see the same issue?

**Comment by bluepnume** [comment]
Is there something missing from the newer major versions that I can help with?

**Comment by bluepnume** [comment]
Can you do `zoid.postRobot.CONFIG.ACK_TIMEOUT = 5000;`?

**Comment by zsakmany** [comment]
Yepp, it works! Thank you! 👍
