### ISSUE TITLE
Styling change to zoid container results in restricted height.

### ISSUE THREAD

**Issue by jimwe** [krakenjs/zoid#208]
A change at version 8.0.6 affected the way the our content displays (or doesn't display) in the zoid container. I suspect it may be this change:  https://github.com/krakenjs/zoid/commit/ef78528e04e82295d79849d7ab7c019d120b8196#diff-c9b7344a832080ac087fcbe301bf5a71

We have been creating our zoid component with height and width of 100% which previously worked to fill the element that the component gets rendered into. Before the styling change at 8.0.6, the zoid container and the zoid-outlet would both get width=100% and height=100%. Now only the zoid-outlet gets that styling and the zoid container (in my case) is 18px high so the iFrame is not visible.

I'm wondering if this was intentional and will be the go-forward behavior in which case we can change our code to suit by setting the size of our zoid component appropriately - set it to a px size rather than 100%.

We tried using autoSize but the results were not as expected.

**Comment by bluepnume** [comment]
Can you try the latest version? I think this should be resolved.

**Comment by jimwe** [comment]
Yes, looks to be working fine in 9.0.2. -Thanks!
