### ISSUE TITLE
Error: Could not find driver for framework: react

### ISSUE THREAD

**Issue by sesteva** [krakenjs/zoid#212]
"zoid": "^8.0.9"
"react": "^16.7.0",
"react-dom": "^16.7.0",

Im able to use render method to inject the cross domain component, but when I try to register in React the following error comes up 

> Error: Could not find driver for framework: react

Implementation:

index.html

```
    <script src="./zoid.js"></script>
    <script src="http://localhost:3001/mycomponent.js"></script>
```

App.js

```
import React from "react";
import ReactDOM from "react-dom";
let MyLoginReactZoidComponent = window.MyZoidComponent.driver("react", {
  React: React,
  ReactDOM: ReactDOM
});

```

**Comment by bluepnume** [comment]
Are you using `dist/zoid.frameworks.js`?

**Comment by sesteva** [comment]
Ahh..ok.. documentation has no mention for it. I'll create a PR to update docs.
I got it working but the props are only passed on instantiation.
If the React app changes the props, these don't seem to be propagated down to the wrapped components.

Parent App

`<MyReactZoidComponent username="{this.state.username}" auth={this.state.auth} />`

Child App

```
class App extends Component {  
  render() {
    return (
      <div className="App">
        <header className="App-header">
          {this.props.auth ? (
            `Hello ${this.props.username}`
          ) : (
            <img src={logo} className="App-logo" alt="logo" />
          )}
        </header>
      </div>
    );
  }
}
```

**Comment by oluomotoso** [comment]
@sesteva ,
I have been trying to get zoid to work for a couple of days now. Can't seem to figure it out, I've read all the demos and try all the help I could get. It just seems not to work. I will really appreciate if you can help in any way you can. With Regards
