### ISSUE TITLE
iframe accessible (initial/fallback content)

### ISSUE THREAD

**Issue by twig-openlearning** [krakenjs/zoid#215]
is there a way to pre-populate the iframe with some initial content.
this is a requirement for WCAG / accessibility

https://www.accessibilityoz.com/factsheets/coding/developer-checklist/ (see "COD_A3: IFRAMEs must have a text alternative")

**Comment by bluepnume** [comment]
Absolutely: https://github.com/krakenjs/zoid/blob/master/docs/api.md#prerendertemplate-opts--htmlelement

**Comment by twig-openlearning** [comment]
thanks for the super quick response!
