### ISSUE TITLE
Unable to run build 

### ISSUE THREAD

**Issue by oluomotoso** [krakenjs/zoid#217]
ERROR in ./node_modules/zoid/src/index.js 5:7
Module parse failed: Unexpected token (5:7)
You may need an appropriate loader to handle this file type.
| export { PopupOpenError } from 'belter/src';
| export { create, destroyAll, Component } from './component';
> export type { ZoidComponent } from './component';
| export { PROP_TYPE, PROP_SERIALIZATION, CONTEXT, CLASS } from './constants';.

I have been trying to get zoid work for more than five days. Obviously I'm doing something totally wrong. I've tried with webpack and start react scripts.

I will appreciate all the help I can get
Thanks

**Comment by bluepnume** [comment]
Can you share the code you're using to import zoid?

**Comment by oluomotoso** [comment]
import {create} from 'zoid/src';

export let ApiZoidComponent = create({
    tag: 'games-api',
    url: process.env.REACT_APP_URL
});

**Comment by bluepnume** [comment]
Can you try importing from just 'zoid'?

**Comment by oluomotoso** [comment]
Ok, thanks for your assistance. I did that and I was able to build but having 
import {ApiZoidComponent} from './zoid/zoidapi'
ReactDOM.render(<ApiZoidComponent {...window.xprops}/>, document.querySelector('RenderGamesApi'));

**Comment by oluomotoso** [comment]
Parent Application
import * as ApiZoidComponent from './zoid/zoidlotto'
ReactDOM.render(<ApiZoidComponent {...window.xprops}/>, document.querySelector('RenderGamesApi'));

Cross Domain Application
<!DOCTYPE html>

<head>

    <script src="http://localhost:4001/bundle.js"></script>
</head>

<body>


<div id="RenderGamesApi"></div>



<div id="result"></div>

<script>

    // Render the component and pass down props to the iframe

    ApiZoidComponent.render({


    }).render('#RenderGamesApi');

</script>

</body>

But Still I got this error
Uncaught Error: Target container is not a DOM element.
    at l (bundle.js:82)
    at Object.render (bundle.js:95)
    at Module.<anonymous> (bundle.js:137)
    at n (bundle.js:1)
    at Object.<anonymous> (bundle.js:66)
    at n (bundle.js:1)
    at bundle.js:1
    at bundle.js:1
l @ bundle.js:82
render @ bundle.js:95
(anonymous) @ bundle.js:137
n @ bundle.js:1
(anonymous) @ bundle.js:66
n @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
api-test:21 Uncaught ReferenceError: ApiZoidComponent is not defined
    at api-test:21

**Comment by bluepnume** [comment]
1. Are you calling `ApiZoidComponent.driver('react', { React, ReactDOM })` before you try to render? See the example here: 

https://github.com/krakenjs/zoid/blob/master/demo/frameworks/react/index.htm#L21-L24
https://github.com/krakenjs/zoid/blob/master/demo/frameworks/react/index.htm#L51

2. `window.xprops` will only be available in the child frame (based on the props you pass in through the parent). So `<ApiZoidComponent {...window.xprops}/>` doesn't look correct to me.

3. Does `RenderGamesApi` element exist? This doesn't look like a valid selector to me...

**Comment by oluomotoso** [comment]
The Application itself is a react application, routing fully controlled by react. What I need to do is to render one of the application route as a cross domain component.
2\. Does `RenderGamesApi` element ? Yes it exist. I have been on this for quite a while and I need it to work as alot depends on it.

I believe I maybe doing somethings fundamentally wrong. Kindly spare a few minutes to help

**Comment by bluepnume** [comment]
Is `RenderGamesApi` the id? in which case the selector should be `#RenderGamesApi`.

Can you host the code somewhere? I'd be happy to help you debug if I can try it out.

**Comment by oluomotoso** [comment]
@bluepnume, I have added you to the repository. Kindly check ...
Thank you

**Comment by oluomotoso** [comment]
Hello @bluepnume, Kindly let me know !

**Comment by bluepnume** [comment]
You've added me to the repo, but you're going to need to give me more details. I can't even see where you're trying to render `ApiZoidComponent`. Can you link me to the relevant parts of the code?

**Comment by bluepnume** [comment]
What would be best is if you can host the app somewhere so I can go in and debug with it running.

**Comment by oluomotoso** [comment]
Thank you @bluepnume ,

Please check out this JSFiddle

[https://jsfiddle.net/oluomotoso/6o2uyxhn/4/]

**Comment by bluepnume** [comment]
This doesn't run -- `https://www.lixombet.com/static/js/main.chunk.js` isn't a valid javascript file

**Comment by oluomotoso** [comment]
Hi @bluepnume, thanks for the help so far. I have updated the JsFiddle. I think I've made some progress, however the spinner is just loading, not rendering the content. Kindly guide me on what to do.  Thanks

**Comment by bluepnume** [comment]
`https://www.lixombet.com/static/js/main.chunk.js` is still not a valid javascript file. it's returning html.

**Comment by oluomotoso** [comment]
please check this JS Fiddle. https://jsfiddle.net/oluomotoso/ez0qp9t4/30/.

Thanks ...

**Comment by bluepnume** [comment]
Are you loading zoid.frame.js and zoidlotto.js inside the frame too? That's necessary for the frame to start communicating with the parent and for the spinner to go away

**Comment by oluomotoso** [comment]
thank you very much for your help. Words will fail me to say how appreciative I am of your assistance. Good job bro and thank you very much
