### ISSUE TITLE
Closeing Popup while prerenderTemplate is still active throws Window Closed error

### ISSUE THREAD

**Issue by sytong** [krakenjs/zoid#218]
I render a zoid component as a popup.
When I try to close the popup while the prerenderTemplate is still active (the spinner). 
I got this error.

```
Uncaught Error: Window closed
    at index.js:550
    at _loop (promise.js:161)
    at ZalgoPromise._proto.dispatch (promise.js:152)
    at ZalgoPromise._proto.resolve (promise.js:96)
    at _loop (promise.js:212)
    at ZalgoPromise._proto.dispatch (promise.js:152)
    at ZalgoPromise._proto.resolve (promise.js:96)
    at promise.js:353
    at _loop (promise.js:161)
    at ZalgoPromise._proto.dispatch (promise.js:152)
```

This is thrown by this function in the `ParentComponent`:
```
    close() : ZalgoPromise<void> {
        return ZalgoPromise.try(() => {
            this.component.log(`close`);
            return this.event.trigger(EVENT.CLOSE);

        }).then(() => {
            if (this.child) {
                this.child.close.fireAndForget().catch(noop);
            }

            return this.destroy(new Error(`Window closed`), false);
        });
    }
```

I wonder is there any way to gracefully close the popup while prerenderTemplate is still active without causing this error?

**Comment by bluepnume** [comment]
The difficulty here is that closing the window prior to it being loaded rejects the `render()` promise since it's a failure during the render process. And if that render promise rejection isn't handled, it'll result in an uncaught error.

So in theory, you can `render().catch(() => { ... })` to handle/suppress that error.
