### ISSUE TITLE
CSP Issue with Zoid

### ISSUE THREAD

**Issue by kksanghi** [krakenjs/zoid#220]
When we are trying to integrate CSP with zoid it's failing run time we are getting below issue

![image](https://user-images.githubusercontent.com/16228568/53190495-bc2ded00-362f-11e9-97b8-fecc27ae614b.png)

How to fix this, we did tried adding nonce when adding reference for Zoid

**Comment by muhaimincs** [comment]
Can you share the code?

**Comment by satyamTheSong** [comment]
How did this get resolved? can someone please link the solutions? @bluepnume
