### ISSUE TITLE
zoid Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

### ISSUE THREAD

**Issue by jordi-farre** [krakenjs/zoid#222]
Hello,

We are getting this error when we call the render method:

zoid Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

It's related with one prop (string) that we are sending to the iframe, that has Turkish characters. We tried to set serialization to base64 in props definition, but it didn't work.

Thank you.

**Comment by bluepnume** [comment]
Can you share an example of the string?

**Comment by jordi-farre** [comment]
Hi! Yes for example "Tişört ve bluz".

I checked your code and internally executes a btoa to transform it to base64. 

Seems there is some problem with btoa and some characters:

https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa

**Comment by gui-gui** [comment]
I've had the same problem, and although I would not suggest this as a permanent solution, it has worked in solving the problem. I'm not sure about the side effects of this change I've made though.

in `zoid.js` at `function base64encode(str)` i've changed the simple `return btoa(str)` to:  

```
        function base64encode(str) {
            if ("function" == typeof btoa) {
                return btoa(encodeURIComponent(str).replace(/%([0-9A-F]{2})/g,
                    function toSolidBytes(match, p1) {
                        return String.fromCharCode('0x' + p1);
                    }));
            }
            if ("undefined" != typeof Buffer) return Buffer.from(str, "utf8").toString("base64");
            throw new Error("Can not find window.btoa or Buffer");
        }
```
did the same for the decoding part at `function parseChildWindowName(windowName)`

was 

```
...
                try {
                    return JSON.parse(function(str) {
                        if ("undefined" != typeof window && "function" == typeof window.atob) return window.atob(str);
                        if ("undefined" != typeof Buffer) return Buffer.from(str, "base64").toString("utf8");
                        throw new Error("Can not find window.atob or Buffer");
                    }(encodedPayload));
                }
...
```
and now i have 
```
...
                try {
                    return JSON.parse(function(str) {
                        if ("undefined" != typeof window && "function" == typeof window.atob) {
                            return decodeURIComponent(atob(str).split('').map(function(c) {
                                return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
                            }).join(''));
                        }
                        if ("undefined" != typeof Buffer) return Buffer.from(str, "base64").toString("utf8");
                        throw new Error("Can not find window.atob or Buffer");
                    }(encodedPayload));
...
```

this was based on https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#Solution_2_%E2%80%93_escaping_the_string_before_encoding_it

**Comment by Borcha91** [comment]
Hey @bluepnume , I'm affected right now by this issue but since you migrated the base64 encode and decoder to the belter utilities here: https://github.com/krakenjs/belter/blob/master/src/util.js#L9 maybe it makes sense to improve the code/decode in the utilities so all the characters are accepted as the window name. If you agree I can make the PR there to fix the issue.

**Comment by KiyeopYang** [comment]
This shoud be fixed asap

**Comment by KiyeopYang** [comment]
> I've had the same problem, and although I would not suggest this as a permanent solution, it has worked in solving the problem. I'm not sure about the side effects of this change I've made though.
> 
> in `zoid.js` at `function base64encode(str)` i've changed the simple `return btoa(str)` to:
> 
> ```
> function base64encode(str) {
>     if ("function" == typeof btoa) {
>         return btoa(encodeURIComponent(str).replace(/%([0-9A-F]{2})/g,
>             function toSolidBytes(match, p1) {
>                 return String.fromCharCode('0x' + p1);
>             }));
>     }
>     if ("undefined" != typeof Buffer) return Buffer.from(str, "utf8").toString("base64");
>     throw new Error("Can not find window.btoa or Buffer");
> }
> ```
> 
> did the same for the decoding part at `function parseChildWindowName(windowName)`
> 
> was
> 
> ```
> ...
> try {
>     return JSON.parse(function(str) {
>         if ("undefined" != typeof window && "function" == typeof window.atob) return window.atob(str);
>         if ("undefined" != typeof Buffer) return Buffer.from(str, "base64").toString("utf8");
>         throw new Error("Can not find window.atob or Buffer");
>     }(encodedPayload));
> }
> ...
> ```
> 
> and now i have
> 
> ```
> ...
> try {
>     return JSON.parse(function(str) {
>         if ("undefined" != typeof window && "function" == typeof window.atob) {
>             return decodeURIComponent(atob(str).split('').map(function(c) {
>                 return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
>             }).join(''));
>         }
>         if ("undefined" != typeof Buffer) return Buffer.from(str, "base64").toString("utf8");
>         throw new Error("Can not find window.atob or Buffer");
>     }(encodedPayload));
> ...
> ```
> 
> this was based on https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#Solution_2_%E2%80%93_escaping_the_string_before_encoding_it

`if (window) {
	(function() {
		if (window.btoa) {
			const previousBtoa = window.btoa;
			function insideBtoa(str) {
				return encodeURIComponent(str).replace(
					/%([0-9A-F]{2})/g,
					function toSolidBytes(match, p1) {
						return String.fromCharCode('0x' + p1);
					},
				);
			}
			window.btoa = function(input) {
				return previousBtoa(insideBtoa(input));
			};
		}
		if (window.atob) {
			const previousAtob = window.atob;
			function outsideAtob(str) {
				return decodeURIComponent(
					str
						.split('')
						.map(function(c) {
							return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
						})
						.join(''),
				);
			}
			window.atob = function(input) {
				return outsideAtob(previousAtob(input));
			};
		}
	})();
}
`

**Comment by bluepnume** [comment]
I'm going to close this for now. I think polyfilling `atob` and `btoa` is the best approach. I'd rather not bloat zoid with additional polyfills.

**Comment by doublemarked** [comment]
This pops up for us regularly on modern browsers. It seems odd to me that a polyfill would be necessary. It's dependent on the content, not on the browser, right? Are there browsers that this does not occur with?

**Comment by bluepnume** [comment]
Reopening.

> This pops up for us regularly on modern browsers. It's dependent on the content, not on the browser, right? Are there browsers that this does not occur with?

I'd count it as a bug that btoa/atob in modern browsers don't work by default with unicode; but I'm sure there are good backwards compat reasons that can't be fixed. It would be good if a new api were exposed that we could use.

But on second thought, requiring devs to polyfill this or pass in their own custom serializer because of a browser issue, seems like overkill.

I'm debating just using the first solve from https://stackoverflow.com/questions/30106476/using-javascripts-atob-to-decode-base64-doesnt-properly-decode-utf-8-strings -- given that:

1. This is just a one-off cost when rendering components for the first time (future `postMessage`s don't need to be base64 encoded).
2. It's the smallest of the solutions from https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding

So let's do this. I'll try to find some time -- otherwise if anyone likes, please make a PR into `belter` with a couple of tests and I'll gladly merge it in.

https://github.com/krakenjs/belter/blob/master/src/util.js#L8-L29

**Comment by doublemarked** [comment]
@bluepnume thank you very much for reconsidering!

**Comment by KyorCode** [comment]
We are also in desperate need for this fix as it currently blocks us for going into production with our software.

**Comment by bluepnume** [comment]
New zoid version published!
