### ISSUE TITLE
How to create an Embeddable js code for other website to Embeed

### ISSUE THREAD

**Issue by NangoliJude** [krakenjs/zoid#223]
I have a simple widget in react js using zoid im stack on how to create the share embeed code for other website to embeed. I need some help

**Comment by muhaimincs** [comment]
i thought simply provide one line javascript

**Comment by NangoliJude** [comment]
How do i go about that? do u have any example I can look at?

**Comment by muhaimincs** [comment]
```html
<script
    src="https://yoursite.com/js?client-id=SB_CLIENT_ID">
  </script>
```

I serve that static `js` file using nodejs where I can process `SB_CLIENT_ID` to lookup database and pull necessary information. Then the script which generated by webpack earlier will be serve using `ejs` package to rewrite all the `ejs` variable with the data I have from database. That's it. I can serve react app then
