### ISSUE TITLE
Want access to close handler along with default ContainerTemplate

### ISSUE THREAD

**Issue by umartopia** [krakenjs/zoid#227]
I wanted to have an access to "close" property/handle via ContainerTemplate method. However, once I do that, there is no way for me to use the default ContainerTemplate of zoid and I ended up re-implementing the ContainerTemplate (by referring paypal example shared by you).

If you could provide a cleaner way to access "close" handler without the need to re-defining ContainerTemplate, it would be great.

**Comment by bluepnume** [comment]
Can you elaborate a little on what you're hoping to do? Are you trying to extend the functionality of the existing container template?

**Comment by umartopia** [comment]
Not really. I just want access to "close" handle, but do not want to redefine the containerTemplate.

If there is a way to access "close" handle(r) without re-redifning the containerTemplate, I could use that. But I did not find a way to achieve it.

**Comment by bluepnume** [comment]
Sure -- but can you describe the use-case? The close handler is exposed to props, and when you're initializing the component -- so what you're trying to do may already be possible.

**Comment by umartopia** [comment]
The current use case is like the following:

1) I am currently using React for my website
2) I have zoid creation/definition in common place
3) So when I navigate to a different page, I am trying to close the previous instance and use the new one (to avoid issue related to can't add zoid with same tag something)

**Comment by bluepnume** [comment]
Zoid should automatically close the component when react unmounts the current page. Is that not working as expected?

> zoid creation/definition in common place

Are you calling `zoid.create` multiple times for the same component? Ideally that should be avoided

**Comment by umartopia** [comment]
I think zoid.create was called multiple times and to overcome this issue, I had opted for closing the previous instance and re-opening the new instance approach (using close handler).
