### ISSUE TITLE
Unable to get props in Vue Js

### ISSUE THREAD

**Issue by oluomotoso** [krakenjs/zoid#230]
Thanks for this gem of a package. However, I'm unable to get the passed window.xprops in a vue js component. I'm able to do this perfectly with reactjs but now I need to implement with vuejs.

Kindly assist,

**Comment by oluomotoso** [comment]
@bluepnume

**Comment by bluepnume** [comment]
Hi! Are you loading the component (`zoid.create()` call) in the child window/frame?
