### ISSUE TITLE
Package size

### ISSUE THREAD

**Issue by richie-south** [krakenjs/zoid#233]
Is there something we can do to reduce the package size? 
Could we maybe exclude code that not everybody uses something like how lodash does it with imports example:
``ìmport merge from 'lodash/merge'``` (this only imports code that is used in the merge function and nothing else) 😃

**Comment by bluepnume** [comment]
https://github.com/krakenjs/zoid/blob/master/dist/zoid.frame.min.js

^ This bundle is about as small as I can get it (21k gzipped) with just iframe based components.

If you can identify any redundant parts of the build, or anything that can be further minified or tree-shaken, I'm definitely open to considering them for inclusion 👍
