### ISSUE TITLE
Zoid Usage in React: Error: Driver support not enabled 

### ISSUE THREAD

**Issue by joyfulelement** [krakenjs/zoid#234]
## Issue

Hi, been trying to learn how Zoid work with a React app. However, I am struggling to get the React web app to work with Zoid because it throws `Driver support not enabled` error at runtime.

<img width="986" alt="debugging" src="https://user-images.githubusercontent.com/5963818/57389360-fbc49980-7187-11e9-83a9-a27f9fed7703.png">

The debugging attempt shows that the `_proto` is undefined on line 3316 in `zoid.js`, I am really not sure what's missing in the current setup in React App and couldn't find any relevant documentation or issue about it. 

**Any guidance for how to get around this issue would be very much appreciated.**

## Code
Here are the code that reproduce the issue:

In React app
```
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import zoid from 'zoid';

export let ZoidComponent = zoid.create({
  tag: 'zoid-component',
  url: 'http://localhost:8080/Index.html'
});

let ReactComponent = ZoidComponent.driver('react', {
  React: React,
  ReactDOM: ReactDOM
});

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      hasError: false
    };
  }

  componentDidCatch(error, info) {
    this.setState({ hasError: true, error });
  }

  render() {
    return this.state.hasError ? (
      <div>Error occurred when rendering React App</div>
    ) : (
      <ReactComponent loadComponent={'load Component'}/>
    );
  }
}

export default App;
```
## Dependencies

Here are the references of the dependencies:

```
"dependencies": {
    "react": "16.8.6",
    "react-dom": "16.8.6",
    "redux": "4.0.1",
    "zoid": "9.0.24"
  },
  "devDependencies": {
    "@babel/core": "7.4.4",
    "@babel/preset-env": "7.4.4",
    "@babel/preset-react": "7.0.0",
    "babel-loader": "8.0.5",
    "webpack": "4.30.0",
    "webpack-cli": "3.3.2",
  }
```
Tried older version of React and React-dom as follow and doesn't work either and throws the same error
```
    "react": "16.2.0",
    "react-dom": "16.2.1",
```

**Comment by awei01** [comment]
FYI, same error is also present on `demo/advanced/react-end-to-end/index.htm`

**Comment by KiyeopYang** [comment]
this must be fixed asap

**Comment by bluepnume** [comment]
I've fixed `demo/advanced/react-end-to-end/index.htm`. Please use `dist/zoid.frameworks.js`

**Comment by sainiankit** [comment]
I'm facing the same problem on `9.0.27`. Is this fix not released yet ?
<img width="426" alt="Screenshot 2019-06-12 at 10 00 34 AM" src="https://user-images.githubusercontent.com/4703046/59323609-ffa08a00-8cf8-11e9-894b-4bcbbaad437a.png">

**Comment by bluepnume** [comment]
Did you start using `dist/zoid.frameworks.js`?

**Comment by sainiankit** [comment]
`import zoid from 'zoid/dist/zoid.frameworks';

const ZoidComponent = zoid.create({
    tag: 'hello-world',
    url: `./child.html`,
    dimensions: {
      width: '600px',
      height: '400px'
    },
    prerenderTemplate() {
      const html = document.createElement('html')
      html.innerHTML = '<body>Pre-render</body>'
      return html
    },
    contexts: {
      popup: true
    }
  });

  let ReactComponent = ZoidComponent.driver('react', {
    React: React,
    ReactDOM: ReactDOM
  });`

That's how it should be imported ?

**Comment by sainiankit** [comment]
`import * as zoid from 'zoid/dist/zoid.frameworks.js';` solves that problem but I get this in the console afterwards
<img width="718" alt="Screenshot 2019-06-12 at 12 44 20 PM" src="https://user-images.githubusercontent.com/4703046/59330677-bd367780-8d0f-11e9-893a-11916c3c2c52.png">
