### ISSUE TITLE
Wrong version published to NPM

### ISSUE THREAD

**Issue by ashbrener** [krakenjs/zoid#236]
NB Note that wrong version (v6.0.74) of zoid has been published to NPM as "latest" instead of v9.0.25

![image](https://user-images.githubusercontent.com/116340/58011983-b5f6c200-7af3-11e9-93a3-13624ea8f21c.png)

**Comment by awei01** [comment]
Looks ok now. npm showing `9.0.27`

**Comment by drank** [comment]
Checked today and it is again 6.0.76 - https://www.npmjs.com/package/zoid

How to install the latest version via npm?

**Comment by bluepnume** [comment]
I've fixed this. But please specify `"^9"` in your package.json.
