### ISSUE TITLE
Popup component not working on Edge and IE11 (same domain issue)

### ISSUE THREAD

**Issue by clanga-flywire** [krakenjs/zoid#237]
Create a popup component using zoid on a server (eg: localhost:3000)

```javascript
xxx: zoid.create({
    tag: 'xxx',
    url: 'http://xxx/xxx',
    bridgeUrl: 'http://xxx/bridge.html',
    defaultContext: 'popup',
	...
})
```
Trigger the component from another server (eg: localhost:4000)

```javascript
xxx(values).render();
```

**Observations:**
- Works fine in Chrome but not in Edge and IE11
- Here are the errors from Edge and IE11
edge: `0: Expected window to be same domain`
IE11: `SCRIPT5022: All post-robot messaging strategies failed: Error at Anonymous function (...) at Wn.postrobot_post_message ... SCRIPT5022: Expected window to be same domain`
- On IE11 the behavior is not consistent. Sometimes the first error is not thrown

Do you have any idea what might cause these issues?

**Comment by bluepnume** [comment]
Do you have a page where I can try to repro?

**Comment by clanga-flywire** [comment]
It seems that the issue was fixed in the meantime.
I tested today with the latest version `9.0.28` and it works.
