### ISSUE TITLE
default function which require no setup for end user

### ISSUE THREAD

**Issue by muhaimincs** [krakenjs/zoid#238]
How do I provide a function to trigger resize of the iframe where user of my script don't have to setup like this

```js
<script>
    MyLoginComponent({

        prefilledEmail: 'foo@bar.com',

        onLogin: function(email) {
            console.log('User logged in with email:', email);
        }

    }).render('#container');
</script>
```
as simple like this
```js
<script>
    MyLoginComponent().render('#container');
</script>
```

As you can see above, I want if the user does not provide the `onLogin` function, that function will behave to its own implementation. I mean we have default implementation for that function. How do I achieve that. FYI, I just want to make a custom resize function

**Comment by bluepnume** [comment]
You can pass a default value when you create the component:

```javascript
const MyComponent = zoid.create({
  props: {
    myProp: {
      type: 'function',
      default: () => {
        return () => {
          console.warn('myProp was called')
        };
      }
    }
  }
});
```
