### ISSUE TITLE
Zoid iframe support does not work with Chrome 76, 77

### ISSUE THREAD

**Issue by StanculescuDaniel** [krakenjs/zoid#240]
Zoid iframe support does not work with Chrome 76, 77 which will be released soon. The props are not passed down into window.xprops which is undefined inside the zoid iframe.
In Chrome 75 the problem is not reproducible. 

Further investigation shows that on Chrome 76, 77 window.name is empty inside the child page and zoid depends on the name to make the connection between parent and child pages. The error starts in https://github.com/krakenjs/zoid/blob/a27434d5452a2f18a41116baceb654c414e0e294/src/child/window.js at line 38 where window.name is used:

`export function getChildPayload() : ?ChildPayload {
    try {
        return parseChildWindowName(window.name);
    } catch (err) {
        // pass
    }
}`

The thrown exception is not logged.

Notes:
- The parent and the child pages must be on different domains.
- zoid version: 9.0.27
- The Chrome 76, 77 changes can be found here: https://www.chromestatus.com/features#milestone%3D76 
- Chrome 77 can be downloaded here: 
 https://www.google.com/intl/en/chrome/canary/

**Comment by bluepnume** [comment]
Strange. I just tested with Canary 77 and saw no problems. How are you testing?

**Comment by StanculescuDaniel** [comment]
> Strange. I just tested with Canary 77 and saw no problems. How are you testing?

The child page must be on a different domain than the parent page.
I've created a small app based on example provided on zoid npm page: 

[zoid.zip](https://github.com/krakenjs/zoid/files/3275525/zoid.zip)

Use a http server to fetch the static files in the archive, then replace the `url` in `script-where-my-login-component-is-defined.js` with the one your http server have.
To simulate a different parent/child domain you can open from file explorer `parentpage.html`. It remains stuck in the spinning state in Chrome 77. 

Let me know if you manage to reproduce.

**Comment by bluepnume** [comment]
Ahh I see. Are you loading the parent page from a webserver, or from a local file?

I get the same issue with a local file. I'd recommend testing this using a webserver. I'll dig into the issue, but using local files typically causes all kinds of issues with cross-domain comms.

**Comment by StanculescuDaniel** [comment]
It reproduces when parent is loaded from a webserver as well. For the attached `zoid.zip` example in my previous comment:

- Place `script-where-my-login-component-is-defined.js`, `zoid.frame.js`, `parentpage.html` on **webserver nr 1** 

- Place `script-where-my-login-component-is-defined.js`, `zoid.frame.js`, `childpage.html` on **webserver nr 2** 

- Modify `script-where-my-login-component-is-defined.js` from webserver nr. 1 to point to the webserver nr. 2

On Chrome 75 it works well, on Chrome 76, 77 the `window.xprops` is undefined:
![zoid](https://user-images.githubusercontent.com/8004345/59333037-3b8b1d80-8d00-11e9-870d-cfeb116679f9.PNG)

It can also be tested with PayPal integration (https://developer.paypal.com/docs/checkout/integrate/#4-set-up-the-transaction) which uses zoid. 
I added this page https://stage-www.888casino.com/paypal.html which adds PayPal buttons.  
On Chrome 75 it works well, on Chrome 76, 77 the PayPal buttons no longer do their job because `window.xprops` is undefined:

![paypal](https://user-images.githubusercontent.com/8004345/59333181-78571480-8d00-11e9-9a95-efb834a710e6.PNG)

**Comment by StanculescuDaniel** [comment]
@bluepnume, any updates about the fix for this issue? 
According to https://www.chromestatus.com/features/schedule Chrome will start to receive automatic updates to version 76 on Jul 30.

**Comment by bluepnume** [comment]
Very weird. I can repro on your test page, but not on https://developer.paypal.com/demo/checkout/#/pattern/client

Digging into this. Thanks for the help reproing.

**Comment by bluepnume** [comment]
I did find a race condition setting the window name, which looks like a likely culprit. I can't test whether it fixed the paypal button in canary until tomorrow -- but in the mean time can you try the fix and let me know if it helped?

https://github.com/krakenjs/zoid/commit/d88b96a28de7e4dffa6d1bfdcf687208679913d8

I've published a new version of zoid with the fix included.

**Comment by bluepnume** [comment]
OK. I repro'd the race-condition in a simplified environment at http://bluesuncorp.co.uk/icv4/foo.htm

Got it so the bug appears in canary but not standard chrome. The issue was the window name was being set AFTER the window location. That works in chrome but not canary.

I'll roll out the paypal sdk with this fix this week. Thanks again for catching this! As mentioned zoid is published with the fix.

**Comment by StanculescuDaniel** [comment]
I tested zoid 9.0.28 on both Chrome 76 and 77 and the problem is gone. Thank you for the fix!

**Comment by doublemarked** [comment]
@StanculescuDaniel thank you tremendously for identifying and isolating this issue, and of course to @bluepnume for fixing it. I invested only a mere hour tonight in what would have been much worse otherwise.
