### ISSUE TITLE
How to add a custom header while fetching the child component with the specified url ?

### ISSUE THREAD

**Issue by sainiankit** [krakenjs/zoid#242]
Would it be possible to add a custom header to the request fetching the iframe child ? The intent is to pass Access Token along with the request.

**Comment by sainiankit** [comment]
I'm assuming that won't be possible because, if I use an Ajax call response as the **dataURL for src attribute of my iframe**, I would not be able to use postMessage API as I intended to, to pass messages to the child app loaded in the iFrame.

Is there a way round ?

**Comment by umartopia** [comment]
can't you pass accessToken as part of the defined zoid props?

**Comment by sainiankit** [comment]
The application I'm trying to load itself requires the user to be authenticated. (It's not a standalone frontend). That is why, I wanted to pass the access/id token in the headers.

> can't you pass accessToken as part of the defined zoid props?
I'm using query-params for that now, however passing it in the heders was most desirable.

**Comment by bluepnume** [comment]
There's no way to pass a custom header to an iframe, unfortunately. Otherwise I would definitely add support to zoid.

Could you set up a new url which handles the request and proxies it over the original url, and adds the auth header?

**Comment by satyamTheSong** [comment]
> There's no way to pass a custom header to an iframe, unfortunately. Otherwise I would definitely add support to zoid.
> 
> Could you set up a new url which handles the request and proxies it over the original url, and adds the auth header?

Hi Bluepnume, can you share some link or sample code on how to do it while using zoid to launch the iFrame
