### ISSUE TITLE
Not able to access popup window from parent

### ISSUE THREAD

**Issue by josephdgrady** [krakenjs/zoid#244]
After the parent app renders the component like so: 

window.MyLoginZoidComponent({
    }).render('#container', 'popup');

is there any way for the parent app to access the popup window so that it can close it, change the URL, etc.?

**Comment by bluepnume** [comment]
To close it:

```javascript
// Create an instance
const instance = window.MyLoginZoidComponent({ ... });

// Render the instance
instance.render('#container', 'popup');

// Close the instance
instance.close();
```

**Comment by bluepnume** [comment]
Can you elaborate on when the parent window would change the url?

**Comment by josephdgrady** [comment]
Thanks for the close() info. We are thinking about having multiple popup widgets for our application that our clients could choose from. If they decide to use 2 widgets, they could make the flow seemless - once the first widget's flow is complete, they change the url to the next one (instead of having to close the popup and open a new one).

**Comment by wjdgh329** [comment]
@bluepnume what if we are providing an adaptor with methods that create({...}).render(#container) and one that needs to close this. how would i close that instance when they're just calling methods?

**Comment by bluepnume** [comment]
@wjdgh329 I'm not clear on your question. Can your adapter expose a `close()` method, which calls close() on the zoid component internally?
