### ISSUE TITLE
What is the difference between v6 and v9?

### ISSUE THREAD

**Issue by drank** [krakenjs/zoid#246]
I see there are 2 versions in the releases and in NPM.

What is the difference and why do we need 2 versions? Which one to use?

Thanks.

**Comment by rickyH** [comment]
We're thinking the same thing. v6 or v9? Is one stable one latest features maybe?

**Comment by bluepnume** [comment]
Please use v9. v6 is only still supported for some legacy PayPal products which are unable to upgrade at this time.
