### ISSUE TITLE
One Parent Multiple Children?

### ISSUE THREAD

**Issue by jpmdev** [krakenjs/zoid#247]
Hello,

Can someone tell me if the following setup is possible and if so what setup is required?
Thanks in advance!

My Scenario:
I have a Zoid Parent that is initialized with TAG: "MY_APP" and the URL: "www.foo.com/A".

Zoid Child A, lives on "www.foo.com/A" with the same tag as the parent "MY_APP". A user interacts with a button on Zoid Child A and Zoid child A is redirected (inside the iframe) to "www.foo.com/B" where Zoid Child B resides. Zoid Child B has the same TAG as its sibling and the parent.

Is it possible for the Parent to setup communication with Child B?

**Comment by bluepnume** [comment]
So long as the `tag` matches with the parent, and the domain matches the url that you pass, When zoid is loaded it will assume that it's the same component, and it will start populating `window.xprops`.

That said -- is there a reason not to just load the original zoid component code inside `www.foo.com/B `? Why do you need a different component to be loaded here?

**Comment by jpmdev** [comment]
@bluepnume Ah I see. In my actual scenario the domains are different between Child A and B. Now it makes sense. Thank you!

In regards to your question, Child B would be a completely different application than Child A but both would share the same Parent since they share common callbacks, etc..
