### ISSUE TITLE
Dynamic URL with Vue.js

### ISSUE THREAD

**Issue by drank** [krakenjs/zoid#248]
I cannot seem to find a way to use Zoid with dynamic URL in Vue.js applications.

I have 2 Vue.js applications, running on different domains, the 2nd app runs in an iframe. The source URL for the iframe is dynamic and changes every time the 1st app (the parent) loads. This URL is determined on app1 load and then stored in a Vuex store.

How to create a Zoid Vue component that has the URL provided as a parameter?

I tried:
```
<template>
  <zoid-iframe style="width: 100%"/>
</template>

<script>
import * as zoid from 'zoid/dist/zoid.frameworks.js'
import Vue from 'vue'

export default {
  data () {
    return {
      post: this.$store.state.editor.post
    }
  },
  created () {
    this.$options.components['zoid-iframe'] = zoid.create({
      tag: 'zoid-iframe',
      url: this.post.link + '?impulse_preview'
    }).driver('vue', Vue)
  }
}
</script>
```
but then I get the following exception every time the app hot-reloads:

> [Vue warn]: Error in created hook: "Error: Can not register multiple components with the same tag: zoid-iframe"

In addition, the above approach doesn't look very nice - it feels like a hack.

I also tried creating the Zoid component outside of "export default" and then using the "components" option to define the component:
```
<template>
  <zoid-iframe style="width: 100%"/>
</template>

<script>
import * as zoid from 'zoid/dist/zoid.frameworks.js'
import Vue from 'vue'
import store from '../store/editor'

let ZoidIframe = zoid.create({
  tag: 'zoid-iframe',
  url: store.state.post.link + '?impulse_preview'
})

export default {
  components: {
    'zoid-iframe': ZoidIframe.driver('vue', Vue)
  }
}
</script>
```
but 'store.state.post.link' is always undefined so I still am not able to create the zoid component properly.

Any help would be appreciated.

**Comment by bluepnume** [comment]
You can define `url` as a function which decides which url to use.

```javascript
let ZoidIframe = zoid.create({
  tag: 'zoid-iframe',
  url: () => {
     return '...';
  }
})
```
