### ISSUE TITLE
how to define props that listen to browser url change

### ISSUE THREAD

**Issue by muhaimincs** [krakenjs/zoid#249]
How do I write the definition to listen url of parent change. Here is how code it

```js
props: {
        parentUrl: {
            type:       'string',
            required: false,
            default:  () => {
                return window.location.href;
            }
        }
    },
```

So whenever the location or uri or hash change, fn `parentUrl` will have current value of url and I can trace the change through the `window.xprops.onProps`. Is that possible?

related: #130

**Comment by bluepnume** [comment]
I would be tempted to set this up like so.

In the parent:

```
import { onUrlChange } from './lib';

MyComponent({
    onUrlChange: onUrlChange
})
```

In the child:

```
window.xprops.onUrlChange(newUrl => {
    ...
});
```

This way the child window can register a listener and react when the url changes. You would need to define a `onUrlChange` function which listens for changes and calls a callback though.

```
function onUrlChange(callback) {
    window.addEventListener('hashchange', () => callback())
}
```

**Comment by bluepnume** [comment]
Sure, the code you posted will work. And yes you can expose a function to the child window to cancel too.

**Comment by muhaimincs** [comment]
how do I pass the callback from child?

**Comment by bluepnume** [comment]
In the parent:

```javascript
function onUrlChange(callback) {
    const handler = () => callback();
    window.addEventListener('hashchange', handler);
    return {
        cancel: () => window.removeEventListener('hashchange', handler);
    };
}

const MyComponent = create({
   props: {
         onUrlChange: {
               type: 'function',
               required: false,
               value: () => onUrlChange
         }
   }
})
```

In the child:

```
const listener = xprops.onUrlChange(url => {
    // ...
});

listener.cancel();
```

**Comment by muhaimincs** [comment]
thanks @bluepnume. Much appreciated
