### ISSUE TITLE
Setting `name` attribute of frame

### ISSUE THREAD

**Issue by mdalzell** [krakenjs/zoid#250]
Is there a way to set a custom name attribute for the iframe within the component?  Right now the name is a long string like this:

`__zoid__demo_component__eyJ1aWQiOiJ6b2lkLWNoZWNrb3V0LWJ1dHRvbi0xYmFhNDYyMzQzX210azZudHk2bWptIiwiY29udGV4dCI6ImlmcmFtZSIsInZlcnNpb24iOiI5XzBfMjgiLCJjaGlsZERvbWFpbiI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCIsInBhcmVudERvbWFpbiI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCIsInRhZyI6ImNoZWNrb3V0LWJ1dHRvbiIsInBhcmVudCI6eyJ0eXBlIjoicGFyZW50IiwiZGlzdGFuY2UiOjB9LCJwcm9wcyI6eyJ0eXBlIjoicmF3IiwidmFsdWUiOiJ7fSJ9LCJleHBvcnRzIjoie1wiaW5pdFwiOntcIl9fdHlwZV9fXCI6XCJjcm9zc19kb21haW5fZnVuY3Rpb25cIixcIl9fdmFsX19cIjp7XCJpZFwiOlwiZjg5YzUzZTY5ZV9tdGs2bnR5Nm1qbVwiLFwibmFtZVwiOlwiblwifX0sXCJjbG9zZVwiOntcIl9fdHlwZV9fXCI6XCJjcm9zc19kb21haW5fZnVuY3Rpb25cIixcIl9fdmFsX19cIjp7XCJpZFwiOlwiODdhODQ4MGRmOF9tdGs2bnR5Nm1qbVwiLFwibmFtZVwiOlwiY2xvc2VcIn19LFwiY2hlY2tDbG9zZVwiOntcIl9fdHlwZV9fXCI6XCJjcm9zc19kb21haW5fZnVuY3Rpb25cIixcIl9fdmFsX19cIjp7XCJpZFwiOlwiMGUzNzE0ZWFmY19tdGs2bnR5Nm1qbVwiLFwibmFtZVwiOlwiY2hlY2tDbG9zZVwifX0sXCJyZXNpemVcIjp7XCJfX3R5cGVfX1wiOlwiY3Jvc3NfZG9tYWluX2Z1bmN0aW9uXCIsXCJfX3ZhbF9fXCI6e1wiaWRcIjpcImZmOWQ1ZTE4ZjBfbXRrNm50eTZtam1cIixcIm5hbWVcIjpcInJlc2l6ZVwifX0sXCJvbkVycm9yXCI6e1wiX190eXBlX19cIjpcImNyb3NzX2RvbWFpbl9mdW5jdGlvblwiLFwiX192YWxfX1wiOntcImlkXCI6XCJkOTBkYzIzNWMyX210azZudHk2bWptXCIsXCJuYW1lXCI6XCJ0XCJ9fX0ifQ==__` 

Is this name necessary in order to populate the frame?  I tried manually setting the value within `containerTemplate`, but that did not work.

**Comment by bluepnume** [comment]
Yes, the name is used to pass down initial data/props, so it can't be overridden. Can you let me know why you're trying to set a custom name though? Maybe there's some other way to achieve what you're trying to do.

**Comment by mdalzell** [comment]
Got it, thanks for the response.  Honestly I was just trying to replace the `__zoid__` identifier at the start of the string with my own module name.  Not a big deal if this isn't customizable, but that would be a nice feature in the future.
