### ISSUE TITLE
`window.xprops` sporadically undefined in Firefox 68.0.1

### ISSUE THREAD

**Issue by mdalzell** [krakenjs/zoid#252]
It seems that `window.xprops` is occasionally undefined for my components in Firefox 68.0.1 (it does work some of the time).  Chrome seems to work fine.  

I'm rendering to the body of a parent window from within another zoid component: 
```
export const openModal = props =>
  zoidModalComponent(props).renderTo(window.parent, "body");
```

I'm trying to access the `xprops` via a React component like so:
```
const Parent = () => {
  if (!window.xprops) {
    return <Loading />
  }

  const { property } = window.xprops
  return (
    <Child {...property} />
  )
}
```

**Comment by mdalzell** [comment]
Nevermind, the issue was in how we were dynamically loading in the zoid component scripts

**Comment by russelh15** [comment]
@mdalzell What was your solution?

**Comment by mdalzell** [comment]
@russelh15 My issue was that the source scripts for the zoid were not always loading before the script for the component.  I was trying to be clever with lazy loading the scripts, but that ultimately backfired on me.  This problem was a little insidious, since the issue was almost non-existent in Chrome but somewhat frequent with Firefox, and I'm not entirely sure why.

**Comment by kimutaiRop** [comment]
@russelh15 I have the same problem can you please be clear on how you did it?

**Comment by russelh15** [comment]
@kimutaiRop I can't remember exactly what i did, but it was something about the scripts not loading in the correct order. There was a race condition happening, so be sure load your scripts in the correct order.

Sorry I could not provide a detailed answer, this was a long time ago and I forgot the context of the project.
