### ISSUE TITLE
[Question] Is it possible to render a React app in a zoid iframe

### ISSUE THREAD

**Issue by pnarielwala-tc** [krakenjs/zoid#253]
Hello 👋 

I'm looking to embed a React app into another React (CRA) app using zoid iframes. Is this possible? If so, how do I go about "connecting" the two apps? Specifically implementing this line from the README
```
<script src="script-where-my-login-component-is-defined.js"></script>
```

Thanks!

**Comment by bookRa** [comment]
Hi @pnarielwala-tc 

I wrote a short tutorial for how to deal with this: https://medium.com/@omar.abdelbadie1/cross-domain-react-apps-with-create-react-app-and-zoid-d6caae4380fe?source=friends_link&sk=b49e20b6eb36e782ae0d3a4cf9bb2d80

Hope that helps

**Comment by bluepnume** [comment]
Great article, thanks @bookRa!!

**Comment by jasan-s** [comment]
@bookRa  I watched the video and read tutorial but unclear as to how exactly would i import the app using script tag. you seem to just copy the `MyWidget.js` in the parent.  

What I need to do is the following:

create a zoid component for a specific route in React App A, and then use <script> tag in another Single Page Application (SPA) call it App B (which could be any framework based) to load and render the defined Zoid Component(which is a App A route)

**Comment by adlondon** [comment]
@jasan-s I'm running into the same issue... did you ever find a solution?
