### ISSUE TITLE
Using zoid with multiple component deployments

### ISSUE THREAD

**Issue by carlosouro** [krakenjs/zoid#254]
Hi guys,

I've met Daniel at fullstack conf in London and that's how I came into contact with Zoid.
As I explained to Daniel we are have actually developed something similar in-house and we now considering moving to Zoid instead.

I just need to validate 2 use-cases:

**(1)**
In our case components are deployed into unknown domains (B2B - multiple 3rd parties), so it's really hard for us to have a component definition that would know its own URL.

It would be preferable for us to use zoid like:

```html
<!-- Pull in the login component we defined above -->

<script src="https://hostdomain.com/zoid.js"></script>

<!-- Set up a container for the iframe to be rendered into -->

<div id="container"></div>

<script>
   
   //create component from definition
  //Note: component doesn't know it's own URL, we tell it here
   var MyLoginComponent = new Zoid("https://hostdomain.com/loginform/definition.js")


    // Render the component

    MyLoginComponent({

        prefilledEmail: 'foo@bar.com',

        onLogin: function(email) {
            console.log('User logged in with email:', email);
        }

    }).render('#container');
</script>

```
Does zoid support this kind of use-case in some form or manner?

**(2)**
Another issue which I'm not sure Zoid covers is how to add a component inside an iframe and outside the iframe in which both are the same instance/page. 
I understand you can add a component from within another zoid component and it will reflect on the parent page - but can you access it from multiple components with the same reference/instance? or will it just create a new iframe page everytime?

**Comment by bpartridge** [comment]
For (1) you can have the `url` be a function of the props passed in, like `url: ({props: {url}}) => url`, so it will essentially grab the URL from the props; not sure about (2).

**Comment by bluepnume** [comment]
I'm not sure I totally understand the second use case. Can you describe a little bit more about what you're trying to do? Zoid does support render iframes on the current page (or in the current frame) using `.render()`, or to a remote window (or frame) where zoid is also loaded using `.renderTo()`.
