### ISSUE TITLE
Setting sandbox attribute of frame

### ISSUE THREAD

**Issue by th174** [krakenjs/zoid#258]
Is there some way to set the sandbox attribute of the iframe? Specifically, I want to prevent the child inside the iframe from being able to inject javascript inside the context of the parent.

**Comment by bluepnume** [comment]
Hi @th174.

You can do:

```
const MyComponent = zoid.create({
    attributes: {
        iframe: {
            sandbox: '...'
        }
    }
})
```

That said:

> I want to prevent the child inside the iframe from being able to inject javascript inside the context of the parent

If the iframe is on a different domain, that will be impossible anyway, even without `sandbox`

**Comment by th174** [comment]
> If the iframe is on a different domain, that will be impossible anyway, even without sandbox

That's currently how it is, however, because of some unrelated requirements, I might need to reverse proxy the iframe's domain through the parent's domain. In that case, I would need the sandbox to preserve the same separation separation of permissions.

**Comment by bluepnume** [comment]
Interesting. Could you reverse-proxy onto a subdomain? Otherwise the site will also have same-domain access to any of your server's urls/apis.

**Comment by th174** [comment]
I was hoping to prevent that by revoking allow-same-origin access with the sandbox attribute. Would that not be sufficient?

**Comment by bluepnume** [comment]
That would work, but what if somebody redirects to the page outside of an iframe? Using a subdomain would give an extra layer of security for cases like that.

**Comment by th174** [comment]
After removing the `allow-same-origin` access, I'm getting the following errors:
```xc_homepage_unexpected_listener_init {origin: "null", domain: "http://localhost:8080"


```
Uncaught Error: Unexpected init message from domain null -- expected message from http://localhost:8080
```
