### ISSUE TITLE
Comparison with web components

### ISSUE THREAD

**Issue by mfulton26** [krakenjs/zoid#259]
I would love to see mention and comparison of iframes with Zoid vs. web components (pros and cons of each compared to one another, etc.). Thanks!

**Comment by bluepnume** [comment]
This is definitely a doc or article I'd love to see!

In reality, the main difference is that everything in an iframe is totally sandboxed. Anything which is rendered, any api calls which are made, any data or content or css -- the parent page can't access it or mess with it, which has great security and modularity advantages. Iframes can also access cookies and localStorage on a different domain to the parent page, and use those to render something without exposing that information to the parent page.

It would probably be possible to write a zoid driver (just like the existing react/angular/vue drivers) which exposes a web-component, that ultimately renders a zoid component. So potentially you can have something which feels like a web-component, but is actually a zoid component under the hood with all of the above advantages.

Hope that helps answer your question.

**Comment by sjoedwards** [comment]
Hi @bluepnume, when you say that 'the iframe is totally sandboxed', do you mean that javascript on the parent page can't read or manipulate any of the content contained within the iFrame? Even without the `sandbox` attribute being set?

Thanks,
