### ISSUE TITLE
Demo of zoid with a modal (Like the paypal Checkout)

### ISSUE THREAD

**Issue by blackorzar** [krakenjs/zoid#261]
Hello, could you please create a demo or example of zoid where the iframe shows inside a modal that takes the entire page? Like the paypal checkout where you show the login/password modal.

**Comment by zacel** [comment]
Have you had any success with this? @blackorzar it looks like it can be achieved by setting the width and height of the zoid component to 100% each. I'm looking around seeing where these are set

**Comment by bluepnume** [comment]
Hopefully this is a good starting point: https://github.com/paypal/paypal-checkout-components/blob/master/src/zoid/checkout/component.jsx#L49

This is what we do at PayPal. The background overlay is rendered on the parent page, and the iframe is rendered inside that overlay.

Alternatively, you could write a `containerTemplate` which sets the iframe to be position `absolute` or `fixed` with 100% width and height if you want it to take up the whole page.

**Comment by jasan-s** [comment]
i get the following error : 
>TypeError: Expected jsx element to be a string or a function
