### ISSUE TITLE
Rendering zoid component inside an iframe issues

### ISSUE THREAD

**Issue by kristina1lyba** [krakenjs/zoid#263]
Hey guys! 

We have an issue with PayPal Smart Payment Buttons (which are implemented as a zoid component) and we already asked about it in PayPal's repo (https://github.com/paypal/paypal-checkout-components/issues/1192) but I will try to duplicate it here as well, cause it really hurts us!
 
Our PayPal button is rendered inside an iframe and we would expect the overlay to cover the full window but here what we've got:
![63865411-3615a900-c9ba-11e9-9f9b-f87f09d05ef1](https://user-images.githubusercontent.com/47673738/64068152-c2370300-cc3c-11e9-81a5-62f8935f0121.png)

After checking PayPal's source code, I've found out they are rendering their overlay into the `doc` node that zoid provides (https://github.com/paypal/paypal-checkout-components/blob/1ee91168d389c63292e7cb5ab443454b41fcc31f/src/zoid/checkout/component.jsx#L63):
```
        containerTemplate: ({ props, context, close, focus, doc, event, frame, prerenderFrame }) => {
                const { locale: { lang } } = props;
                const content = containerContent[lang];

                return (
                    <Overlay
                        context={ context }
                        close={ close }
                        focus={ focus }
                        event={ event }
                        frame={ frame }
                        prerenderFrame={ prerenderFrame }
                        content={ content }
                    />
                ).render(dom({ doc }));
            }
```
and it looks kinda expected, that overlay is rendered only inside an iframe. After checking zoid's source code I would assume they need to render overlay using `renderTo` function and provide topmost `window.parent` node to it (which is not available because of CORS)

But what is interesting that the behavior is different when I am adding PayPal script (extra script, in addition to loaded inside an iframe) into the root `index.html` that registers component in the root window and Overlay starts rendering on the root body, not inside an iframe. 

Does zoid check whether component is inside an iframe and does something with it?
Could you please shed a light on how this works and maybe suggest any way to solve this issue?

I am not sure that loading the second PayPal script is the way to go :)

Really appreciate if you could help us and looking forward for any feedback. 
Thank you!

**Comment by bluepnume** [comment]
> But what is interesting that the behavior is different when I am adding PayPal script (extra script, in addition to loaded inside an iframe) into the root index.html that registers component in the root window and Overlay starts rendering on the root body, not inside an iframe.

Yup!

Each iframe is sandboxed. So we can only render 'up' to a different frame, if the component is also loaded in the parent level frame. That way the child can communicate up, and draw the overlay you see.
