### ISSUE TITLE
Uncaught Error: Unable to find global parent component window

### ISSUE THREAD

**Issue by SamaneYaghoobi** [krakenjs/zoid#274]
Hi, When I copy & paste the basic demo example and run locally, I get this Error below:

``` 
Uncaught Error: Unable to find global parent component window
    at e.n.getParentComponentWindow (index.js:182)
    at index.js:79
    at Function.e.try (promise.js:409)
    at new e (index.js:62)
    at e.n.registerChild (component.js:238)
    at new e (component.js:186)
    at Module.Ct (component.js:403)
    at login.js:2
 ```

my login.js:

```
window.MyLoginZoidComponent = zoid.create({
    tag: 'my-login-component',
    url: './login.htm'
});
```

**Comment by bluepnume** [comment]
Are you testing on a web server? Do you have a page where I can try?

**Comment by SamaneYaghoobi** [comment]
@bluepnume I didn't know that I must test on a web server, accidentally run it and It works. 
I think it's better to mention this point in readme or doc.
Thanks a lot for developing Zoid It is really helpfull :)
