### ISSUE TITLE
Setting the height-dimension in percentage does not work

### ISSUE THREAD

**Issue by KristofVDB1** [krakenjs/zoid#281]
I was trying to set the dimensions of the zoid by using the percentages as suggested by the docs. Setting the width to '100%' does work but whenever I change the height-dimension to a percentage, the iframe does not show up. It only works with pixels. I'm currently using Zoid in a React-environment.

Code for reference:

```
    dimensions: {
      width: '800px',
      height: '100%',
    },
```

**Comment by jurajkrivda** [comment]
How you did resolve this?
