### ISSUE TITLE
Remove zoid component

### ISSUE THREAD

**Issue by muhaimincs** [krakenjs/zoid#282]
How do I programmatically remove zoid component

**Comment by mayteio** [comment]
After `zoid.create({tag: 'my-component'})`, I may want to re-create that component however get the error "Can not register multiple components with the same tag:".

`zoid.destroy({tag: 'my-component'})` would be ideal.

**Comment by mayteio** [comment]
Turns out there is this functionality, just not documented. In my case of React:

```
const MyReactZoidComponent = useMemo(() => MyZoidComponent.driver('react', {
    React:    React, 
    ReactDOM: ReactDOM
}), []);

// destroy it on unmount
useEffect(() => {
  return () => { MyReactZoidComponent.destroyActiveComponent() }
}, []);
```

Or, to destroy everything (components, bridge, global);

`zoid.destroy()`

**Comment by bluepnume** [comment]
Hi, you can do:

```
const component = ZoidComponent({ ... });

component.render('#container');

component.close();
```
