### ISSUE TITLE
Why does zoid.destroy() throw an error when it destroys components?

### ISSUE THREAD

**Issue by mayteio** [krakenjs/zoid#288]
I need to create a react zoid component during the render phase, based on some props where we don't know the tag or url ahead of time. My component looks like this;

```javascript
export const ZoidComponent = ({ tag, url, ...props }) => {
  const Zoid = useMemo(() => {
    zoid.destroy()
    return zoid.create({ tag, url }).driver("react", { React, ReactDOM })
  }, [tag, url])

  return Zoid ? <Zoid {...props} /> : null;
}
```

The component above works fine and as expected, however, there's a niggly `Uncaught Error: zoid destroyed all`. I destroy before creating because if I don't, I get the error `Can not register multiple components with the same tag`.

Why does it throw this error if it destroyed it successfully?

**Comment by bluepnume** [comment]
Can you just make `url` a function here, if it needs to be dynamic?

**Comment by mayteio** [comment]
Wouldn’t that be a memory leak? Leaving all these instantiated zoid components in memory?

**Comment by bluepnume** [comment]
Zoid components are designed to be created once, and rendered many times.

Other than dynamically generating the url, why do you need to create the zoid component on each render?

**Comment by mayteio** [comment]
The URL can change rendering different remote components. I ended up using [paciolan/remote-component](https://github.com/Paciolan/remote-component) by publishing commonjs components to npm and it all works natively 🙏

Thanks for your help though.

**Comment by bluepnume** [comment]
Fair enough :)

That's why I suggested setting `url` as a function though. Based on the props passed, you can generate totally different urls.

**Comment by eldiegoman** [comment]
Hi @bluepnume 

So, how could we update the URL of the Zoid-component that was created with a specific URL? I mean, it's possible to update the URL of the component used in the `create` function from Zoid?
