### ISSUE TITLE
process is assumed to exist, which it doesn't in the browser

### ISSUE THREAD

**Issue by ouijan** [krakenjs/zoid#291]
When trying to use a package (which depends on zoid) we get an error that points to:
`https://github.com/krakenjs/zoid/blob/bad7235289672fe374c8f1fd5b000918ff9193e3/index.js`

Which is assuming that `process` exists (which it doesn't in the browser).
If fixed we can remove this polyfill:
```
(window as any).process = {
    env: { DEBUG: undefined },
};
```

Environment Angular 9

**Comment by anthonykhoa** [comment]
Hi! Please assign me.

**Comment by mnicpt** [comment]
You got it, @anthonykhoa !  Happy hacking!

**Comment by anthonykhoa** [comment]
Hi @ouijan 

I was wondering if you could tell me more about this issue. What package did you use that depends on zoid?

**Comment by anthonykhoa** [comment]
Hi guys I made a [PR](https://github.com/krakenjs/zoid/pull/325/files) but it appears to be failing the CI test. I am getting this error:
<img width="744" alt="Screen Shot 2020-10-08 at 12 08 43 PM" src="https://user-images.githubusercontent.com/45890848/95502943-78503e80-095f-11eb-9a48-3bfabbc2f2df.png">
Can I have a suggestion of what to do?

**Comment by musps** [comment]
@anthonykhoa Even the previous commit & test have this error (see the travis test from last commit https://travis-ci.org/github/krakenjs/zoid/builds/732794246)
its not your fault :p
