### ISSUE TITLE
Example embedding zoid in a modern React.js app

### ISSUE THREAD

**Issue by dchersey** [krakenjs/zoid#293]
Hi, I just spent some hours attempting to understand how to use zoid in the context of a modern react.js app, and thought I would share .... I am using react-rails so I don't even have access to the ReactDOM.render code .. instead I use react-router-dom to handle component rendering. 

My test parent app is also React.js so I thought this example could help others: 
```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import zoid from 'zoid';
import './App.css';

const MyZoidComponent = zoid.create({
  tag: 'my-tag',
  url: 'my-url'
});

const MyZoidReactComponent = MyZoidComponent.driver('react', {
  React,
  ReactDOM
});

function App() {
  return (
    <div className="App">
... other componentes
        <MyZoidComponent customText="XYZ" />
... other components
    </div>
  );
}

export default App;
```

That's it --  this renders an iFrame surrounded by the context div that zoid needs to do its magic.

Inside the iFrame (the child component) I render this routed component: 
```javascript
import React from 'react';
import { Route, Switch, BrowserRouter } from 'react-router-dom';
import zoid from 'zoid';
import MyComponent from './MyComponent';


const MyZoidComponent = zoid.create({
  tag: 'my-tag',
  url: 'my-url'
});


function App(props) {
  return (
    <BrowserRouter>
      <Switch>
        <Route
          path="/mypath"
          render={router => (
            <MyComponent {...props} {...window.xprops} {...router} />
          )}
        />
... other routes
      </Switch>
    </BrowserRouter>
  );
}

export default App;
```

MyComponent.js makes no reference to zoid ... it just receives the customText prop in props along with the routing props and anything else I want to give it locally.  It literally has no idea it's running in zoid vs any other React component, which is the way we want it...

**Comment by peter-hartmann** [comment]
It seems ok for a react app to provide multiple zoid components.

```
import React from 'react';
import { Route, Switch, BrowserRouter } from 'react-router-dom';
import zoid from 'zoid';
import MyComponent1 from './MyComponent1';
import MyComponent2 from './MyComponent2';

zoid.create({
  tag: 'my-tag1',
  url: 'my-url/mypath1'
});

zoid.create({
  tag: 'my-tag2',
  url: 'my-url/mypath2'
});

function App(props) {
  return (
    <BrowserRouter>
      <Switch>
        <Route
          path="/mypath1"
          render={router => (
            <MyComponent1 {...props} {...window.xprops} {...router} />
          )}
        />
        <Route
          path="/mypath2"
          render={router => (
            <MyComponent2 {...props} {...window.xprops} {...router} />
          )}
        />
... other routes
      </Switch>
    </BrowserRouter>
  );
}

export default App;
```
Further ```zoid.create``` call could be moved into the Component's code, keeping the App router above clean.
Great for application extensions where an extension provides more than one zoid component.

**Comment by ogrotten** [comment]
@dchersey  Your example react component file is great thank you for that.

What does the file with the `<iframe>` look like? I'm having a problem nailing down any syntax that's needed to show the desired component.

* What url/script is included in the head?
* Is there an actual `<iframe>` element, and if so what attributes does it need?

Thanks again.
