### ISSUE TITLE
window is not defined when using with Nextjs app

### ISSUE THREAD

**Issue by manishajmera** [krakenjs/zoid#294]
ReferenceError: window is not defined
reactive-framework:     at Object../node_modules/post-robot/src/conf/index.js (/home/info/Documents/reactive/myexample/packages/my-lib1/.next/server/static/development/pages/_app.js:4166:77)

**Comment by manishajmera** [comment]
Fixed the issue using dynamic loading in NextJs

**Comment by mayankmx** [comment]
@manishajmera can you please post detailed steps on how you resolved the issue, I am facing this same problem
