### ISSUE TITLE
Why we need to include zoid component created on parent app need to include it on child frame too

### ISSUE THREAD

**Issue by manishajmera** [krakenjs/zoid#295]
Why we need to include zoid component created on parent app need to include it on child frame too. Is there any way without importing zoid component into child

**Comment by vlopez** [comment]
My understanding is that you need to include the component in the child frame too because it internally initializes the channel to communicate with the parent, the is a handshake/initialization process so you need code running and the component registered on both ends.

**Comment by vlopez** [comment]
It is further explained here:
https://youtu.be/UpXavGv7FaI?t=757

**Comment by mnicpt** [comment]
Thank you @vlopez for reponding.  Closing this issue.
