### ISSUE TITLE
How to style both `component` and `iframe`?

### ISSUE THREAD

**Issue by Grabber** [krakenjs/zoid#298]
@bluepnume 

Thank you so much for sharing this with community!

Could you please help me to figure out how to apply css/style on both `component` and `iframe`? I need to inject these styling code:

## zoid-my-login-component-366e992339_mty6mjc6nta
```
display: block;
position: relative;
top: 0px;
right: 0px;
bottom: 0px;
left: 0px;
height: 100%;
```

## iframe
```
border: none;
display: block;
height: 100%;
left: auto;
overflow: auto;
position: fixed;
width: 100%;
```

Thank you so much!

**Comment by kimutaiRop** [comment]
Can anybody answer this... I also need to make the iframe float on top of the main content page like a modal I know how to make the style but how do I inject

**Comment by vlopez** [comment]
Hi,

I have you looked into providing a custom template:
https://github.com/krakenjs/zoid/blob/master/docs/api.md#containertemplate-opts--htmlelement

You get access to the iframe element and you should be able to wrap it around any divs or dom elements you want to as well as to add any css classes that will allow you any style customization.

**Comment by mnicpt** [comment]
I am closing this do to inactivity and a provide solution.  If the solution above does not meet your needs, please reopen and assign to me.  Regards.
