### ISSUE TITLE
Attributes, based on props

### ISSUE THREAD

**Issue by OlehRb** [krakenjs/zoid#308]
In our widget we are using user's location and it seems, like simple
```
...
attributes: {
  iframe: {
    allow: 'geolocation',
  },
},
...
```
doesn't work anymore as Features Policy now requires the iframe's url to be passed explicitly, like: `allow: 'geolocation https://my-awesome-widget.com'`

The problem we faced is that we have different environments: development, stage and production and they all have different urls

The environment is passed as an optional prop, but it seems like there is no way to define attributes, based on props

However, it seems, like we can define iframe's attributes based on props, if we use custom `containerTemplate`, but in this approach we would have to either lose or reimplement / copy-paste the functionality of autoresize and visible / hidden classes switching, which are embedded to the `defaultContainerTemplate`

So, is it possible to either define iframe's attributes, based on props or in some way extend the `defaultContainerTemplate`, so instead of copy-pasting whole default template I could do something, like:

```
...
containerTemplate: (options) => {
  // urls here is just a map, where environment is a key and url is a value
  options.frame.allow = `geolocation ${urls[options.props.environment]}`;

  return defaultContainerTemplate(options);
}
...
```

Any help would be much appreciated

**Comment by bluepnume** [comment]
This is a fair ask. We can probably allow `attributes` to be a function that takes props. If you'd like to make a PR with that change, I'd be happy to merge it in 👍

**Comment by OlehRb** [comment]
@bluepnume, thanks, I will give it a try, most probably during this weekend, and get back to you as soon as I have something :+1:

**Comment by OlehRb** [comment]
@bluepnume, I've submitted a PR https://github.com/krakenjs/zoid/pull/311
It seems to be rather a small change actually

Can you, please, take a look at it?

**Comment by OlehRb** [comment]
@bluepnume , ping

**Comment by OlehRb** [comment]
@bluepnume , sorry to bother you, but when do you expect the version this version to be released to npm?
