### ISSUE TITLE
Update URL from Zoid component

### ISSUE THREAD

**Issue by eldiegoman** [krakenjs/zoid#310]
Hi, 

I need to update the URL value used when the Zoid component was created. I need to update the URL because I'm building the URL including some parameters that change many times. 

It's possible to update the URL value? or destroy the current zoid-component and create another to avoid the common issue related to the creation of a component with the same tag?

**Comment by bluepnume** [comment]
Hi,

When you're setting up props you can set `queryParam: true` to make the prop appear in the url. Is that enough to solve this one?

```
props: {
    foo: {
        type: 'string',
        queryParam: true
    }
}
```

**Comment by eldiegoman** [comment]
Hi,

Works for me, thank you @bluepnume
