### ISSUE TITLE
object deconstruction not working in ie11

### ISSUE THREAD

**Issue by SunilJamkatel** [krakenjs/zoid#318]
Hi, the widget.js file I created contains props with validation. When IE tries to load this script file in the parent, it gives a SCRIPT1010: Expected identifier error,

It seems to be pointing to the argument deconstruction on the following code
`validate: function ({ value, props }) {`

any way I could make this work for IE? Thanks!

**Comment by gregjopa** [comment]
@SunilJamkatel IE 11 does not support [object destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment). You should be able to just take in an object as the params and pull out the values like so:

```js
validate: function (options) {
  const value = options.value;
  const props = options.props;
}
``` 

That should work for IE. Please re-open the issue if you still have troubles.
