### ISSUE TITLE
IE11 Popup Issues

### ISSUE THREAD

**Issue by albernhagen** [krakenjs/zoid#319]
Hello -- I'm working Zoid 9.0.48 and am testing a popup component in IE11.  Everything works great outside of IE.  I've also setup a bridge for IE that is serving correctly.  I can launch the component as a popup, however it seems to close immediately for some reason right after it's opened and the `.catch` handler of `render` is invoked by just saying `Window is closed`, even though no user action prompted this.  The popup window remains open but is now disconnected from zoid.  Any ideas as to what I should be looking for to resolve?

**Comment by albernhagen** [comment]
I should note that the child window can redirect to any URL (even google.com) and the same behavior is exhibited.  I do see some `Access is denied` errors in my IE console, but I believe that might be related to some web component polyfill.

**Comment by gregjopa** [comment]
@albernhagen thanks for reporting the issue. Do you have a demo you can share? Or some screenshots of the errors you're seeing in IE?

**Comment by albernhagen** [comment]
Hey @gregjopa -- I guess this was a case of ask the duck!  When running my local server at `localhost`, IE11 was putting the site in intranet mode 🤦 .  The PayPal checkout elements guide helped me realize to check for it: https://developer.paypal.com/docs/checkout/troubleshoot/internet-explorer/.  Appreciate you following up so quickly!

**Comment by gregjopa** [comment]
@albernhagen Good to hear you got it resolved! 😆 🦆 I'm glad the Troubleshooting IE doc was helpful.
