### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by gutisalex** [krakenjs/zoid#320]
hey, is there any chance you are providing type definitions for this awesome library? ;) I know you have flow running in there but I'd like to use this in a ts library and I am not confident enough to write my own type definition files yet! KR

**Comment by mnicpt** [comment]
@gutisalex This is on our backlog and are looking at this now across all of krakenjs.  Thank you for reaching out to us.

**Comment by nikbelikov** [comment]
any updates here?
