### ISSUE TITLE
Question: Buttons like in Paypal integration

### ISSUE THREAD

**Issue by gutisalex** [krakenjs/zoid#321]
I just have a question on how you made the buttons integration on paypal. As far as I understand you are using a zoid component (buttons) to render an iframe which holds the smart buttons. And when clicking on one of the buttons you are using another zoid component (checkout) to load the checkout page from paypal in a popup. 

So do you use a simple button page on your app page (I found out the url is pointing to /smart/buttons) for the buttons and just use the props to return a onClick function which on the parent triggers the checkout component? Or do you actually build those buttons with the jsx-pragmatic library? 

Because while digging through the paypal-checkout-components src code on github, trying to understand how you set this up I found a folder ui which has jsx files for building buttons as well. For what is this for? Is this for the demo purpose only? In the dev demo you are using jsx-pragmatic to render them on the buttons child page. 

So far...

**Comment by bluepnume** [comment]
Hi,

In the PayPal case, the button iframe is actually calling `Checkout({ ...props }).renderTo(window.parent)` to get the component to render on the parent page.

jsx-pragmatic is only used for rendering the html of the button -- it doesn't handle any of the iframes or interactions.

Zoid -> rendering iframes and popups, dealing with props and communications between those
JSX-Pragmatic -> rendering html (inside or outside of iframes)

**Comment by gutisalex** [comment]
Hmm ok, but is there a html file for the button iframe as a child somewhere to render the buttons (like in the dev demo) or is the whole button container made with zoid and jsx-pragmatic?

**Comment by songz** [comment]
sounds like you got it @gutisalex ! Close issue?

**Comment by mstuart** [comment]
Thanks @songz! @gutisalex, if you're still seeing the issue, feel free to re-open it!
