### ISSUE TITLE
Send updated props to child

### ISSUE THREAD

**Issue by NerdCowboy** [krakenjs/zoid#322]
When a props changes at the parent level, I want to update the props that I'm sending to the child. 

The docs don't seem to cover this, but after trolling through the issues and source code, I found that there's the method `updateProps` at the parent level and it appears that using the `window.xprops.onProps` method at the child level should detect any changes sent through `updateProps`, but I can't seem to get this to work.

I found this reply https://github.com/krakenjs/zoid/issues/162#issuecomment-395495614 that said you can chain a `then` after you `render` the component to the DOM. However, the returned `component` value is always `undefined` from what I'm seeing. I also tried doing`MyComponent().updateProps({ propToUpdate: newValue})` but that doesn't appear to trigger anything in `onProps` in the child. 

```js
// parent
return MyComponent({
    someProp: 1,
  })
    .render('#myDiv')
    .then((component) => { 
       console.log('component', component)) // always undefined
       component.updateProps({someProps: 2}) // obviously won't work if component is undefined
       MyComponent().updateProps({someProps: 2 }) // doesn't seem to do anything
    }
}

//child 
window.xprops.onProps((newProps) => console.log('updated props', newProps)) // never triggered
```
What am I missing here?

**Comment by bluepnume** [comment]
Hi @NerdCowboy -- I added a demo of this here:

http://krakenjs.com/zoid/demo/advanced/props/index.htm

I'm not sure what's going wrong in your case -- but here you can try changing the email on the parent page and have it reflected in the child.

**Comment by NerdCowboy** [comment]
@bluepnume  Really appreciate you making a quick demo! Feel a little stupid as it's pretty obvious in retrospect—I didn't make a variable to render the zoid component, so I wasn't referencing the same instance whenever I tried to trigger `updateProps`.

Hopefully this helps anyone that runs into the same issue: 

If I store MyComponent as a var like the example and use the `updateProps` method on that var, it fixes it and I can see the props being shown in `onProps` in the child now. 

``` js
//parent
const widgetDiv = document.querySelector('#myDiv')
const myWidget = MyComponent({someProp: 1})
myWidget.render('#myDiv')

const widgetObserver = new MutationObserver((mutations) => {
    mutations.forEach((mutation) => {
      if (mutation.type === 'attributes') {
          myWidget.updateProps({someProp: widgetDiv.dataset.someProp})
      } 
   }
}

widgetObserver.observe(widgetDiv, {
    attributes: true,
})

//child 
window.xprops.onProps((newProps) => console.log('updated props', newProps)) // shows the new props
```
