### ISSUE TITLE
popup window closed manually

### ISSUE THREAD

**Issue by MortyPAA** [krakenjs/zoid#333]
Hi guys,
I have a problem handling the manual close of a zoid popup window. The scenario:
- i have a component open as popup
- user clicks on window close button
- onClose is triggered, i get the event, no problem here
- i want now to be able to open again the same component but i cannot.
   -  If i try to render again that component i get an error: **Uncaught Error: Window closed**
   - If i try to create a new component, using the same tag (i need the same page to be opened in the window) i get an error: **Request listener already exists for XXXX on domain * for wildcard window**

How should i treat this scenario in which a zoid popup is closed using the window close button ?

**Comment by MortyPAA** [comment]
Found the problem. It was on my end, sorry for raising this. Will close it.

**Comment by timbohemendinger** [comment]
Hi @MortyPAA, I'm having the same issue. Could you share how you resolved this? Thanks.
