### ISSUE TITLE
Error handling and EVENT.error

### ISSUE THREAD

**Issue by timh770773** [krakenjs/zoid#349]
I'm working on accounting for any potential errors that might get thrown in my application. I see there's an `EVENT.ERROR` listener you can use in the prerenderTemplate. If I don't have any logic that will manually trigger this event, do I need this, if I'm already catching errors on the widget's `render` call? I noticed that if I manually throw an `EVENT.ERROR`, it ends up getting picked up in the render call anyway, which makes sense--so I'm thinking this may not be needed in my case.

Code:
```
   // Initialize the zoid instance
    this.widgetInstance = create({
      tag: 'my-widget',
      url: this.iframeSrc,
      dimensions: {
        width: '100%',
        height: '600px',
      },
      prerenderTemplate: ({ doc, event }) => {
        event.on(EVENT.RENDERED, () => {
          this.screendoorService.toggle(false);
        });

       // Is this necessary?
        event.on(EVENT.ERROR, (err) => {
          this.onFormLoadError(err);
        });
      }
    });

    // Render the zoid component and props into the element
    this.widgetInstance({
      onSuccess: this.successCallback.bind(this),
      onError: this.errorCallback.bind(this)
    }).render(this.widgetContainer.nativeElement).catch((error: Error) => {
      console.log('RENDER ERROR');
      this.onFormLoadError(error);
    });
```

Thanks

**Comment by mnicpt** [comment]
@timh770773 Hope you're enjoying zoid!  It looks to me that you don't need the EVENT.ERROR listener.  We set this up internally and when this event is fired, if you have implemented the `onError` prop, which you have, we will delegate to it.  Also, I don't think you need to catch off of render, as any errors should also be picked up by the `onError` callback.  For the `EVENT.RENDERED`, you may want to consider using the `onRendered` prop and provide a callback.  All of the `EVENT._` delegate to the prop callback handlers.  Hope this helps.  @bluepnume Correct me I'm wrong with any of this.

**Comment by mnicpt** [comment]
@timh770773 Did the feedback help you?

**Comment by timh770773** [comment]
@mnicpt I'm so sorry for the delay, I'd had some trouble getting back into my account before this. This was very helpful and solved my issue! Thank you so much.
