### ISSUE TITLE
npmjs.com latest version is outdated

### ISSUE THREAD

**Issue by lmakarov** [krakenjs/zoid#436]
https://www.npmjs.com/package/zoid has v9.0.86 as the latest published version
<img width="668" alt="Screenshot 2023-05-25 at 14 19 26" src="https://github.com/krakenjs/zoid/assets/1205005/627039b7-dc5a-4b25-ad33-575ff00f21e5">

The latest Github release is [v10.2.4](https://github.com/krakenjs/zoid/releases/tag/v10.2.4) as of right now.

**Comment by gregjopa** [comment]
Hi @lmakarov, we moved zoid under the krakenjs npm scope. You can find the latest here: https://www.npmjs.com/package/@krakenjs/zoid
