### ISSUE TITLE
Expose exports from child

### ISSUE THREAD

**Issue by bluepnume** [krakenjs/zoid#54]
On the child window:

`window.xchild.exports.foo = function() { ... };`

On the parent:

`this.exports.foo();`

Also need a way to declare this on the component definition, so we can mock out function calls until the child is ready.

**Comment by raphaelcosta** [comment]
@bluepnume  it's possible to listen for messages on child and send from parent?

**Comment by bluepnume** [comment]
@raphaelcosta so yeah, that's totally possible right now:

1. Set up a listener and send a message with https://github.com/krakenjs/post-robot (used by xcomponent internally)

2. Use an approach like this: https://github.com/krakenjs/xcomponent/issues/53

This issue is to brainstorm ways to make that easier / more automatic in xcomponent.

**Comment by bluepnume** [comment]
Closing this for now, since this can easily be achieved with just props (calling a prop with exports from the child). Not sure if a new built-in mechanism would be that advantageous.
