### ISSUE TITLE
Automatically add scroll to the lightbox

### ISSUE THREAD

**Issue by ghost** [krakenjs/zoid#71]
Hi @bluepnume,

It seems that xcomponent allows dimensions in percentage now. Cool.
However, when the lighbox content is overflow over the maximum height, it should add a scroll automatically.

In the example below, I tried to add the 'scrolling: true' but still no luck.

```
window.MyLightbox = xcomponent.create({

    autoResize: true,

    sandboxContainer: false,

    dimensions: {
        width: '90%',
        height: '50%'
    },

    scrolling: true,

    containerTemplate: xcomponent.containerTemplate,

    // The html tag used to render my component
    tag: 'my-lightbox-component',

    // The url that will be loaded in the iframe or popup, when someone includes my component on their page
    url: '/lightbox',

    // The properties they can (or must) pass down to my component
    props: {

        onComplete: {
            type: 'function'
        }
    }
});
```

The result:
![screen shot 2017-03-27 at 3 35 29 pm](https://cloud.githubusercontent.com/assets/21060051/24348225/28fc95d0-1305-11e7-8ccb-15ccf96b0123.png)

Thanks,
Ky

**Comment by bluepnume** [comment]
Hey sorry just saw this issue. I'll take a look. We have a component which allows scrolling so not sure why this isn't working for you. Is the problem there in every browser?

**Comment by kms-ky-truong** [comment]
Hey @bluepnume ,

I reproduced it on Safari and Chrome.
Maybe I'm not using "scrolling" the right way?

Thanks,
Ky

**Comment by bluepnume** [comment]
Closing this as any combination of CSS and attributes can be added to enable scrolling; zoid doesn't really need to know about the specific details.
