### ISSUE TITLE
Enhancement: Toggle CSS class on xcomponent container.

### ISSUE THREAD

**Issue by mmairs9** [krakenjs/zoid#92]
I like the ability of being able to resize the surronding xcomponent container on the parent site. It would be even better if we could give the child component the ability to apply a class to its container instead of just having the resize option.

**Comment by bluepnume** [comment]
Hey sorry I missed this issue when you first posted it -- was out on vacation and missed the notification.

I'd rather not add special library support for this since it can be done fairly easily through a prop with a default value:

```
let MyComponent = xcomponent.create({

    addClass: {
        type: 'function',
        value: function(selector, className) {
            document.querySelector(selector).classList.add(className);
        }
    }
});
```

**Comment by mmairs9** [comment]
That should do the trick! thanks!
