### ISSUE TITLE
Width is defined with pixels when dimensions.width is defined with percentage 

### ISSUE THREAD

**Issue by shikshik** [krakenjs/zoid#97]
First of all, good job!
We set the config to have 100% width and height but it renders the width with pixels.
The style should be 100% instead of dynamic pixel sizing, it will also solve an unwanted horizontal scroll bar after height resize.

How can we do it?
It seems like a bug, what do you think?

**Comment by bluepnume** [comment]
Hey @shikshik -- thanks for the report. You're right, ideally it should be defined in %. I'll check on this.

**Comment by bluepnume** [comment]
Are you still seeing this issue?

**Comment by shikshik** [comment]
I'm sorry I missed your response. But since we reported the issue, we found alternatives and fixed all the problems.
Probably you also updated the library. If we will find similar issues, I will report back. Thanks!
